# Energy ANN

## Importing labraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Data Preprocessing

In [2]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

### Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

## Building the model

In [6]:
ann = tf.keras.models.Sequential() ##initializing the ANN model

## Adding the hidden layers
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

## Adding the output layer
ann.add(tf.keras.layers.Dense(units = 1))

##binary classification: activation = sigmoid
##no binary = softmax
#regression = no activation function

## Training the model

In [8]:
ann.compile(optimizer = 'adam',loss = 'mean_squared_error')

In [9]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 833us/step - loss: 204845.1719
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 192750.8906
Epoch 3/100
240/240 [==============================] - 0s 841us/step - loss: 154001.8750
Epoch 4/100
240/240 [==============================] - 0s 950us/step - loss: 94195.7422
Epoch 5/100
240/240 [==============================] - 0s 979us/step - loss: 55132.3477
Epoch 6/100
240/240 [==============================] - 0s 826us/step - loss: 35091.9609
Epoch 7/100
240/240 [==============================] - 0s 866us/step - loss: 21384.3574
Epoch 8/100
240/240 [==============================] - 0s 970us/step - loss: 13163.5459
Epoch 9/100
240/240 [==============================] - 0s 846us/step - loss: 9226.8867
Epoch 10/100
240/240 [==============================] - 0s 755us/step - loss: 6974.1914
Epoch 11/100
240/240 [==============================] - 0s 872us/step - loss: 5218.1616
Epoch 12/100
240/240 [==========

240/240 [==============================] - 0s 779us/step - loss: 21.3841
Epoch 97/100
240/240 [==============================] - 0s 728us/step - loss: 21.4512
Epoch 98/100
240/240 [==============================] - 0s 710us/step - loss: 21.4760
Epoch 99/100
240/240 [==============================] - 0s 766us/step - loss: 21.4733
Epoch 100/100
240/240 [==============================] - 0s 909us/step - loss: 21.4106


## Predicting

In [10]:
y_pred = ann.predict(X_test)

In [17]:

np.set_printoptions(precision = 2, threshold = 10000)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_pred),1)),axis = 1)) 


[[431.98 431.23]
 [458.72 460.01]
 [462.89 461.14]
 [448.99 445.9 ]
 [458.13 451.29]
 [430.25 432.68]
 [473.37 477.5 ]
 [456.8  459.68]
 [474.55 477.5 ]
 [446.82 444.99]
 [442.37 444.37]
 [441.94 437.04]
 [445.06 442.34]
 [441.22 440.74]
 [438.91 436.55]
 [454.58 460.24]
 [445.21 448.66]
 [437.89 432.94]
 [451.69 452.82]
 [427.94 432.2 ]
 [425.97 430.96]
 [432.38 434.65]
 [474.18 473.56]
 [440.33 434.47]
 [448.35 450.92]
 [452.76 452.82]
 [482.   485.94]
 [445.02 435.47]
 [452.28 448.96]
 [466.9  465.89]
 [477.43 482.52]
 [462.17 465.05]
 [474.11 475.51]
 [468.8  466.71]
 [469.87 472.42]
 [434.27 434.64]
 [466.74 467.97]
 [479.98 481.86]
 [434.29 437.72]
 [472.3  470.49]
 [446.57 449.04]
 [466.64 468.15]
 [457.17 457.94]
 [479.87 486.4 ]
 [443.96 443.52]
 [440.26 442.23]
 [433.6  430.61]
 [438.66 439.72]
 [470.45 467.98]
 [440.66 433.36]
 [458.23 448.74]
 [463.98 464.39]
 [441.23 443.06]
 [467.82 470.23]
 [463.89 467.21]
 [443.65 449.1 ]
 [483.93 487.33]
 [482.03 473.73]
 [460.24 461.9