# Energy ANN

## Importing labraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Data Preprocessing

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

### Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

## Building the model

In [7]:
ann = tf.keras.models.Sequential() ##initializing the ANN model

## Adding the hidden layers
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

## Adding the output layer
ann.add(tf.keras.layers.Dense(units = 1))

##binary classification: activation = sigmoid
##no binary = softmax
#regression = no activation function

## Training the model

In [8]:
ann.compile(optimizer = 'adam',loss = 'mean_squared_error')

In [9]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 3ms/step - loss: 203898.1875
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 186317.4688
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 138960.2188
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 82684.8281
Epoch 5/100
240/240 [==============================] - 0s 924us/step - loss: 46791.1758
Epoch 6/100
240/240 [==============================] - 0s 837us/step - loss: 25839.4609
Epoch 7/100
240/240 [==============================] - 0s 850us/step - loss: 14566.0625
Epoch 8/100
240/240 [==============================] - 0s 897us/step - loss: 9707.5215
Epoch 9/100
240/240 [==============================] - 0s 884us/step - loss: 7107.2046
Epoch 10/100
240/240 [==============================] - 0s 874us/step - loss: 5315.7598
Epoch 11/100
240/240 [==============================] - 0s 900us/step - loss: 4025.8574
Epoch 12/100
240/240 [=================

240/240 [==============================] - 1s 2ms/step - loss: 21.5691
Epoch 98/100
240/240 [==============================] - 0s 836us/step - loss: 21.3866
Epoch 99/100
240/240 [==============================] - 0s 964us/step - loss: 21.4584
Epoch 100/100
240/240 [==============================] - 0s 872us/step - loss: 21.4769


## Predicting

In [10]:
y_pred = ann.predict(X_test)

In [11]:

np.set_printoptions(precision = 2, threshold = 10000)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_pred),1)),axis = 1)) 


[[430.55 431.23]
 [458.91 460.01]
 [463.08 461.14]
 [448.38 445.9 ]
 [458.09 451.29]
 [428.91 432.68]
 [473.31 477.5 ]
 [456.6  459.68]
 [474.9  477.5 ]
 [445.89 444.99]
 [441.48 444.37]
 [441.07 437.04]
 [444.66 442.34]
 [440.37 440.74]
 [437.61 436.55]
 [454.47 460.24]
 [444.95 448.66]
 [436.94 432.94]
 [450.92 452.82]
 [426.75 432.2 ]
 [424.46 430.96]
 [430.94 434.65]
 [474.85 473.56]
 [438.72 434.47]
 [447.33 450.92]
 [452.46 452.82]
 [481.75 485.94]
 [444.33 435.47]
 [452.05 448.96]
 [466.89 465.89]
 [477.33 482.52]
 [462.25 465.05]
 [474.46 475.51]
 [468.6  466.71]
 [469.98 472.42]
 [433.12 434.64]
 [466.41 467.97]
 [480.86 481.86]
 [433.09 437.72]
 [472.78 470.49]
 [445.84 449.04]
 [466.55 468.15]
 [457.02 457.94]
 [480.42 486.4 ]
 [443.52 443.52]
 [439.43 442.23]
 [432.63 430.61]
 [437.91 439.72]
 [470.52 467.98]
 [439.82 433.36]
 [457.76 448.74]
 [463.76 464.39]
 [439.96 443.06]
 [467.79 470.23]
 [463.21 467.21]
 [443.05 449.1 ]
 [484.32 487.33]
 [482.5  473.73]
 [460.29 461.9

In [35]:
final_accuracy = []
for i in range(0,len(y_pred)):
    final_accuracy.append(abs(y_pred[i]-y_test[i]))

In [46]:
from math import sqrt
mean = 0
std = 0

for i in range(0,len(y_pred)):
    mean+=final_accuracy[i] 
    
mean = mean/len(y_pred)

for i in range(0,len(y_pred)):
    std+=((final_accuracy[i]-mean)*(final_accuracy[i]-mean))/len(y_pred)
std = round(sqrt(std),2)

In [47]:
print('The mean of the error rate is: ',mean)
print('The standard deviation of the error rate is: ',std)

The mean of the error rate is:  [3.58]
The standard deviation of the error rate is:  2.7
