# Titanic Prediction 

### Importing the libraries

In [2]:
###General DS libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

###Preprocessing 
from sklearn.impute import SimpleImputer ##Missing Values
from sklearn.compose import ColumnTransformer##Encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler##Feature Scaling

##Training AND Models
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, SVR
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

#Evaluation
from sklearn.metrics import confusion_matrix, accuracy_score

### Importing the data

In [3]:
train_dataset = pd.read_csv('train.csv')
test_dataset = pd.read_csv('test.csv')
test_dataset_2_sub = pd.read_csv('test.csv') 

In [4]:
train_dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### Creating training variables

In [5]:
X = train_dataset.iloc[:, 2:].values
y = train_dataset.iloc[:, 1].values

test_dataset = test_dataset.iloc[:, 1:].values

In [6]:
X_ds = pd.DataFrame(X)
X_ds.head()

0                                                  1       2     3  4  5  \
0  3                            Braund, Mr. Owen Harris    male  22.0  1  0   
1  1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0  1  0   
2  3                             Heikkinen, Miss. Laina  female  26.0  0  0   
3  1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  1  0   
4  3                           Allen, Mr. William Henry    male  35.0  0  0   

                  6        7     8  9  
0         A/5 21171     7.25   NaN  S  
1          PC 17599  71.2833   C85  C  
2  STON/O2. 3101282    7.925   NaN  S  
3            113803     53.1  C123  S  
4            373450     8.05   NaN  S

We now need to delete the Tickets, Names and Cabin columns as they are not significant to our prediction

In [7]:
X = np.delete(X, [1,6,8], axis = 1)##Deleting for the training data

np.set_printoptions(threshold=np.inf)
X

array([[3, 'male', 22.0, 1, 0, 7.25, 'S'],
       [1, 'female', 38.0, 1, 0, 71.2833, 'C'],
       [3, 'female', 26.0, 0, 0, 7.925, 'S'],
       [1, 'female', 35.0, 1, 0, 53.1, 'S'],
       [3, 'male', 35.0, 0, 0, 8.05, 'S'],
       [3, 'male', nan, 0, 0, 8.4583, 'Q'],
       [1, 'male', 54.0, 0, 0, 51.8625, 'S'],
       [3, 'male', 2.0, 3, 1, 21.075, 'S'],
       [3, 'female', 27.0, 0, 2, 11.1333, 'S'],
       [2, 'female', 14.0, 1, 0, 30.0708, 'C'],
       [3, 'female', 4.0, 1, 1, 16.7, 'S'],
       [1, 'female', 58.0, 0, 0, 26.55, 'S'],
       [3, 'male', 20.0, 0, 0, 8.05, 'S'],
       [3, 'male', 39.0, 1, 5, 31.275, 'S'],
       [3, 'female', 14.0, 0, 0, 7.8542, 'S'],
       [2, 'female', 55.0, 0, 0, 16.0, 'S'],
       [3, 'male', 2.0, 4, 1, 29.125, 'Q'],
       [2, 'male', nan, 0, 0, 13.0, 'S'],
       [3, 'female', 31.0, 1, 0, 18.0, 'S'],
       [3, 'female', nan, 0, 0, 7.225, 'C'],
       [2, 'male', 35.0, 0, 0, 26.0, 'S'],
       [2, 'male', 34.0, 0, 0, 13.0, 'S'],
       [3, 'f

In [8]:
test_dataset = np.delete(test_dataset, [1,6,8], axis = 1)##Deleting for the testing data

np.set_printoptions(threshold=np.inf)
test_dataset

array([[3, 'male', 34.5, 0, 0, 7.8292, 'Q'],
       [3, 'female', 47.0, 1, 0, 7.0, 'S'],
       [2, 'male', 62.0, 0, 0, 9.6875, 'Q'],
       [3, 'male', 27.0, 0, 0, 8.6625, 'S'],
       [3, 'female', 22.0, 1, 1, 12.2875, 'S'],
       [3, 'male', 14.0, 0, 0, 9.225, 'S'],
       [3, 'female', 30.0, 0, 0, 7.6292, 'Q'],
       [2, 'male', 26.0, 1, 1, 29.0, 'S'],
       [3, 'female', 18.0, 0, 0, 7.2292, 'C'],
       [3, 'male', 21.0, 2, 0, 24.15, 'S'],
       [3, 'male', nan, 0, 0, 7.8958, 'S'],
       [1, 'male', 46.0, 0, 0, 26.0, 'S'],
       [1, 'female', 23.0, 1, 0, 82.2667, 'S'],
       [2, 'male', 63.0, 1, 0, 26.0, 'S'],
       [1, 'female', 47.0, 1, 0, 61.175, 'S'],
       [2, 'female', 24.0, 1, 0, 27.7208, 'C'],
       [2, 'male', 35.0, 0, 0, 12.35, 'Q'],
       [3, 'male', 21.0, 0, 0, 7.225, 'C'],
       [3, 'female', 27.0, 1, 0, 7.925, 'S'],
       [3, 'female', 45.0, 0, 0, 7.225, 'C'],
       [1, 'male', 55.0, 1, 0, 59.4, 'C'],
       [3, 'male', 9.0, 0, 1, 3.1708, 'S'],
       [

### Taking care of missing data

In [9]:
X_describe = pd.DataFrame(X)
X_describe.describe()

0     1      2    3    4       5    6
count   891   891  714.0  891  891  891.00  889
unique    3     2   88.0    7    7  248.00    3
top       3  male   24.0    0    0    8.05    S
freq    491   577   30.0  608  678   43.00  644

In [10]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")##Computing SI of the numerical training data
imputer.fit(X[:,2:3].reshape(-1, 1))
X[:,2:3] = imputer.transform(X[:,2:3])

imputer = SimpleImputer(missing_values=np.nan, strategy="most_frequent")##Computing SI of the categorical training data
imputer.fit(X[:,-1].reshape(-1, 1))
X[:,-1] = imputer.transform(X[:,-1].reshape(-1, 1)).ravel()

In [11]:
X_describe = pd.DataFrame(X)
X_describe.describe()

0     1           2    3    4       5    6
count   891   891  891.000000  891  891  891.00  891
unique    3     2   89.000000    7    7  248.00    3
top       3  male   29.699118    0    0    8.05    S
freq    491   577  177.000000  608  678   43.00  646

In [12]:
test_ds_describe = pd.DataFrame(test_dataset)
test_ds_describe.describe()

0     1      2    3    4       5    6
count   418   418  332.0  418  418  417.00  418
unique    3     2   79.0    7    8  169.00    3
top       3  male   21.0    0    0    7.75    S
freq    218   266   17.0  283  324   21.00  270

In [13]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")##Computing SI of the numerical testing data
imputer.fit(test_dataset[:,2:4].reshape(-1, 1))
test_dataset[:,2:4] = imputer.transform(test_dataset[:,2:3])

imputer.fit(test_dataset[:,5:6].reshape(-1, 1))
test_dataset[:,5:6] = imputer.transform(test_dataset[:,5:6])

imputer = SimpleImputer(missing_values=np.nan, strategy="most_frequent")##Computing SI of the categorical testing data
imputer.fit(test_dataset[:,-1].reshape(-1, 1))
test_dataset[:,-1] = imputer.transform(test_dataset[:,-1].reshape(-1, 1)).ravel()

In [14]:
test_ds_describe = pd.DataFrame(test_dataset)
test_ds_describe.describe()

0     1       2       3    4       5    6
count   418   418  418.00  418.00  418  418.00  418
unique    3     2   80.00   80.00    8  170.00    3
top       3  male   13.65   13.65    0    7.75    S
freq    218   266   86.00   86.00  324   21.00  270

### Encoding the Independent Variable

In [15]:
for gender in range(0,len(X)):##encoding the gender column
    if X[gender, 1]== 'female':
        X[gender, 1] = 0
    else:
        X[gender, 1] = 1 
        
for gender in range(0,len(test_dataset)):##encoding the gender column
    if test_dataset[gender, 1]== 'female':
        test_dataset[gender, 1] = 0
    else:
        test_dataset[gender, 1] = 1 


In [16]:
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[-1])], remainder = 'passthrough')##Encoding the Embarked columns
X = np.array(ct.fit_transform(X))

ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[-1])], remainder = 'passthrough')##Encoding the Embarked columns
test_dataset = np.array(ct.fit_transform(test_dataset))

### Splitting the dataset into the Training set and Test set

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

### Evaluating Models

We will create an accuracy DF that contains all accuracy rate of the models we'll test.

First we'll try to check all the models that don't require feature scaling:

In [18]:
##Decision Tree Regression
regressor = DecisionTreeRegressor(random_state = 0)
pred = regressor.fit(X_train, y_train)    
y_pred = regressor.predict(X_test)

for prediction in range(0,len(y_pred)):
    if(y_pred[prediction]>0.5):
        y_pred[prediction]=1
    else:
        y_pred[prediction]=0
        
acc_DT_reg = round(accuracy_score(y_test, y_pred)*100,2)
acc_DT_reg

76.54

In [19]:
#Linear Regression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

for prediction in range(0,len(y_pred)):
    if(y_pred[prediction]>0.5):
        y_pred[prediction]=1
    else:
        y_pred[prediction]=0
        
acc_linear_reg = round(accuracy_score(y_test, y_pred)*100,2)
acc_linear_reg

79.33

In [20]:
#Polynomial Regression deg = 2

poly_reg_2 = PolynomialFeatures(degree = 2)
X_poly = poly_reg_2.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

y_pred = regressor.predict(poly_reg_2.transform(X_test))

for prediction in range(0,len(y_pred)):
    if(y_pred[prediction]>0.5):
        y_pred[prediction]=1
    else:
        y_pred[prediction]=0

acc_poly_2 = round(accuracy_score(y_test, y_pred)*100,2)

#Polynomial Regression deg = 3

poly_reg_3 = PolynomialFeatures(degree = 3)
X_poly = poly_reg_3.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

y_pred = regressor.predict(poly_reg_3.transform(X_test))

for prediction in range(0,len(y_pred)):
    if(y_pred[prediction]>0.5):
        y_pred[prediction]=1
    else:
        y_pred[prediction]=0

acc_poly_3 = round(accuracy_score(y_test, y_pred)*100,2)

#Polynomial Regression deg = 4

poly_reg_4 = PolynomialFeatures(degree = 4)
X_poly = poly_reg_4.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

y_pred = regressor.predict(poly_reg_4.transform(X_test))

for prediction in range(0,len(y_pred)):
    if(y_pred[prediction]>0.5):
        y_pred[prediction]=1
    else:
        y_pred[prediction]=0

acc_poly_4 = round(accuracy_score(y_test, y_pred)*100,2)

acc_poly_2, acc_poly_3, acc_poly_4

(82.68, 78.77, 77.65)

In [21]:
#Random Forest Regression
regressor = RandomForestRegressor(n_estimators = 100,  random_state = 0)
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

for prediction in range(0,len(y_pred)):
    if(y_pred[prediction]>0.5):
        y_pred[prediction]=1
    else:
        y_pred[prediction]=0

acc_RFR = round(accuracy_score(y_test, y_pred)*100,2)
acc_RFR

79.89

And now for the models that require Scaling:

In [22]:
##Feature Scaling

sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [23]:
##Decision Tree Classification

classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)

acc_DT_class = round(accuracy_score(y_test, y_pred)*100,2)
acc_DT_class

80.45

In [24]:
##KNN

classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)
acc_KNN = round(accuracy_score(y_test, y_pred)*100,2)
acc_KNN

79.89

In [25]:
##SVM

classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)

acc_SVM = round(accuracy_score(y_test, y_pred)*100,2)
acc_SVM

81.01

In [26]:
#SVR
classifier = SVR(kernel = 'rbf',)
classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)

for prediction in range(0,len(y_pred)):
    if(y_pred[prediction]>0.5):
        y_pred[prediction]=1
    else:
        y_pred[prediction]=0

acc_SVR = round(accuracy_score(y_test, y_pred)*100,2)
acc_SVR

81.56

In [27]:
##Logistic Regression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)

acc_log_reg = round(accuracy_score(y_test, y_pred)*100,2)
acc_log_reg

81.01

In [28]:
##Naive Bayes
classifier = GaussianNB()
classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)

acc_naive = round(accuracy_score(y_test, y_pred)*100,2)
acc_naive

77.65

In [29]:
#Random Forest Classification
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)

acc_RFC =  round(accuracy_score(y_test, y_pred)*100,2)
acc_RFC

79.33

In [31]:
#Cat Boost
from catboost import CatBoostClassifier
classifier = CatBoostClassifier()
classifier.fit(X_train_scaled, y_train)

y_pred = classifier.predict(X_test_scaled)

acc_cat =  round(accuracy_score(y_test, y_pred)*100,2)
acc_cat

Learning rate set to 0.008911
0:	learn: 0.6867990	total: 188ms	remaining: 3m 8s
1:	learn: 0.6834269	total: 199ms	remaining: 1m 39s
2:	learn: 0.6778791	total: 203ms	remaining: 1m 7s
3:	learn: 0.6725415	total: 206ms	remaining: 51.4s
4:	learn: 0.6665678	total: 209ms	remaining: 41.6s
5:	learn: 0.6604573	total: 211ms	remaining: 35s
6:	learn: 0.6544134	total: 213ms	remaining: 30.2s
7:	learn: 0.6490369	total: 215ms	remaining: 26.7s
8:	learn: 0.6437391	total: 217ms	remaining: 23.9s
9:	learn: 0.6384861	total: 219ms	remaining: 21.7s
10:	learn: 0.6344320	total: 221ms	remaining: 19.8s
11:	learn: 0.6298669	total: 222ms	remaining: 18.3s
12:	learn: 0.6253179	total: 224ms	remaining: 17s
13:	learn: 0.6209436	total: 225ms	remaining: 15.8s
14:	learn: 0.6166348	total: 227ms	remaining: 14.9s
15:	learn: 0.6133803	total: 228ms	remaining: 14s
16:	learn: 0.6086834	total: 229ms	remaining: 13.2s
17:	learn: 0.6049383	total: 230ms	remaining: 12.5s
18:	learn: 0.6012950	total: 231ms	remaining: 11.9s
19:	learn: 0.597

304:	learn: 0.3588989	total: 523ms	remaining: 1.19s
305:	learn: 0.3587107	total: 524ms	remaining: 1.19s
306:	learn: 0.3586417	total: 525ms	remaining: 1.19s
307:	learn: 0.3584928	total: 526ms	remaining: 1.18s
308:	learn: 0.3584428	total: 528ms	remaining: 1.18s
309:	learn: 0.3583476	total: 528ms	remaining: 1.18s
310:	learn: 0.3581195	total: 529ms	remaining: 1.17s
311:	learn: 0.3578616	total: 530ms	remaining: 1.17s
312:	learn: 0.3577570	total: 531ms	remaining: 1.17s
313:	learn: 0.3576837	total: 532ms	remaining: 1.16s
314:	learn: 0.3575979	total: 533ms	remaining: 1.16s
315:	learn: 0.3574277	total: 535ms	remaining: 1.16s
316:	learn: 0.3572367	total: 536ms	remaining: 1.15s
317:	learn: 0.3570932	total: 537ms	remaining: 1.15s
318:	learn: 0.3569357	total: 538ms	remaining: 1.15s
319:	learn: 0.3568486	total: 539ms	remaining: 1.15s
320:	learn: 0.3566640	total: 541ms	remaining: 1.14s
321:	learn: 0.3564395	total: 542ms	remaining: 1.14s
322:	learn: 0.3563657	total: 544ms	remaining: 1.14s
323:	learn: 

468:	learn: 0.3369221	total: 692ms	remaining: 783ms
469:	learn: 0.3367384	total: 693ms	remaining: 781ms
470:	learn: 0.3363209	total: 694ms	remaining: 780ms
471:	learn: 0.3362590	total: 695ms	remaining: 778ms
472:	learn: 0.3359978	total: 696ms	remaining: 776ms
473:	learn: 0.3359332	total: 697ms	remaining: 774ms
474:	learn: 0.3358914	total: 698ms	remaining: 772ms
475:	learn: 0.3357544	total: 699ms	remaining: 770ms
476:	learn: 0.3356539	total: 700ms	remaining: 768ms
477:	learn: 0.3355568	total: 702ms	remaining: 766ms
478:	learn: 0.3354237	total: 703ms	remaining: 764ms
479:	learn: 0.3353611	total: 704ms	remaining: 763ms
480:	learn: 0.3353598	total: 704ms	remaining: 760ms
481:	learn: 0.3352350	total: 705ms	remaining: 758ms
482:	learn: 0.3352102	total: 706ms	remaining: 756ms
483:	learn: 0.3348696	total: 707ms	remaining: 754ms
484:	learn: 0.3348088	total: 708ms	remaining: 752ms
485:	learn: 0.3347895	total: 709ms	remaining: 750ms
486:	learn: 0.3346885	total: 710ms	remaining: 748ms
487:	learn: 

642:	learn: 0.3172981	total: 864ms	remaining: 479ms
643:	learn: 0.3172587	total: 865ms	remaining: 478ms
644:	learn: 0.3170912	total: 866ms	remaining: 477ms
645:	learn: 0.3170429	total: 867ms	remaining: 475ms
646:	learn: 0.3169938	total: 868ms	remaining: 474ms
647:	learn: 0.3167738	total: 869ms	remaining: 472ms
648:	learn: 0.3166371	total: 871ms	remaining: 471ms
649:	learn: 0.3165682	total: 872ms	remaining: 469ms
650:	learn: 0.3163849	total: 873ms	remaining: 468ms
651:	learn: 0.3163198	total: 874ms	remaining: 466ms
652:	learn: 0.3161619	total: 875ms	remaining: 465ms
653:	learn: 0.3161198	total: 877ms	remaining: 464ms
654:	learn: 0.3160179	total: 878ms	remaining: 462ms
655:	learn: 0.3158941	total: 879ms	remaining: 461ms
656:	learn: 0.3157804	total: 880ms	remaining: 459ms
657:	learn: 0.3157032	total: 881ms	remaining: 458ms
658:	learn: 0.3154781	total: 882ms	remaining: 456ms
659:	learn: 0.3153971	total: 883ms	remaining: 455ms
660:	learn: 0.3150399	total: 884ms	remaining: 453ms
661:	learn: 

929:	learn: 0.2870327	total: 1.19s	remaining: 89.9ms
930:	learn: 0.2869376	total: 1.2s	remaining: 88.6ms
931:	learn: 0.2868174	total: 1.2s	remaining: 87.3ms
932:	learn: 0.2868021	total: 1.2s	remaining: 86ms
933:	learn: 0.2867135	total: 1.2s	remaining: 84.7ms
934:	learn: 0.2866091	total: 1.2s	remaining: 83.4ms
935:	learn: 0.2863231	total: 1.2s	remaining: 82.1ms
936:	learn: 0.2862145	total: 1.2s	remaining: 80.9ms
937:	learn: 0.2861734	total: 1.2s	remaining: 79.6ms
938:	learn: 0.2860070	total: 1.2s	remaining: 78.3ms
939:	learn: 0.2858942	total: 1.21s	remaining: 77ms
940:	learn: 0.2858472	total: 1.21s	remaining: 75.7ms
941:	learn: 0.2857292	total: 1.21s	remaining: 74.4ms
942:	learn: 0.2855769	total: 1.21s	remaining: 73.1ms
943:	learn: 0.2855188	total: 1.21s	remaining: 71.8ms
944:	learn: 0.2852757	total: 1.21s	remaining: 70.5ms
945:	learn: 0.2852179	total: 1.21s	remaining: 69.2ms
946:	learn: 0.2849940	total: 1.21s	remaining: 67.9ms
947:	learn: 0.2849653	total: 1.22s	remaining: 66.7ms
948:	l

82.12

Now we'll evaluate:

In [32]:
models = pd.DataFrame({
    'Model': ['Decision Tree Regression','Linear Regression', 'Polynomial Regression deg = 2',
             'Polynomial Regression deg = 3', 'Polynomial Regression deg = 4',
             'Random Forest Regression', 'Decision Tree Classification', 'KNN',
             'SVM','SVR','Logistic Regression','Naive Bayes', 'Random Forest Classification','CatBoost'],
    'Score': [acc_DT_reg,acc_linear_reg,acc_poly_2,acc_poly_3,acc_poly_4,acc_RFR,
             acc_DT_class,acc_KNN,acc_SVM,acc_SVR,acc_log_reg,acc_naive,acc_RFC,acc_cat]})
models.sort_values(by='Score', ascending = False)

Model  Score
2   Polynomial Regression deg = 2  82.68
13                       CatBoost  82.12
9                             SVR  81.56
8                             SVM  81.01
10            Logistic Regression  81.01
6    Decision Tree Classification  80.45
5        Random Forest Regression  79.89
7                             KNN  79.89
1               Linear Regression  79.33
12   Random Forest Classification  79.33
3   Polynomial Regression deg = 3  78.77
4   Polynomial Regression deg = 4  77.65
11                    Naive Bayes  77.65
0        Decision Tree Regression  76.54

### Applying k-Fold Cross Validation

We will apply K Fold Cross Validation on the top 3 models:

In [33]:
from sklearn.model_selection import cross_val_score

In [34]:
#Cat Boost

accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print('Cat Boost:')
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Learning rate set to 0.008515
0:	learn: 0.6872941	total: 1.59ms	remaining: 1.59s
1:	learn: 0.6841969	total: 2.25ms	remaining: 1.12s
2:	learn: 0.6791454	total: 3.65ms	remaining: 1.21s
3:	learn: 0.6740427	total: 4.76ms	remaining: 1.19s
4:	learn: 0.6689166	total: 5.9ms	remaining: 1.17s
5:	learn: 0.6645332	total: 6.97ms	remaining: 1.15s
6:	learn: 0.6608202	total: 7.74ms	remaining: 1.1s
7:	learn: 0.6555726	total: 8.79ms	remaining: 1.09s
8:	learn: 0.6504307	total: 9.82ms	remaining: 1.08s
9:	learn: 0.6454568	total: 10.7ms	remaining: 1.06s
10:	learn: 0.6404047	total: 12ms	remaining: 1.08s
11:	learn: 0.6354591	total: 13.3ms	remaining: 1.09s
12:	learn: 0.6310966	total: 14.5ms	remaining: 1.1s
13:	learn: 0.6270894	total: 15.6ms	remaining: 1.1s
14:	learn: 0.6233444	total: 16.3ms	remaining: 1.07s
15:	learn: 0.6184840	total: 17.3ms	remaining: 1.06s
16:	learn: 0.6141523	total: 18.2ms	remaining: 1.05s
17:	learn: 0.6104115	total: 19ms	remaining: 1.04s
18:	learn: 0.6061983	total: 20ms	remaining: 1.03s
19

168:	learn: 0.4000500	total: 163ms	remaining: 800ms
169:	learn: 0.3998394	total: 164ms	remaining: 799ms
170:	learn: 0.3996968	total: 164ms	remaining: 797ms
171:	learn: 0.3994506	total: 166ms	remaining: 797ms
172:	learn: 0.3988590	total: 167ms	remaining: 797ms
173:	learn: 0.3987509	total: 167ms	remaining: 793ms
174:	learn: 0.3984603	total: 168ms	remaining: 793ms
175:	learn: 0.3982681	total: 169ms	remaining: 793ms
176:	learn: 0.3978813	total: 170ms	remaining: 792ms
177:	learn: 0.3976146	total: 171ms	remaining: 791ms
178:	learn: 0.3972192	total: 172ms	remaining: 791ms
179:	learn: 0.3967293	total: 174ms	remaining: 791ms
180:	learn: 0.3965248	total: 175ms	remaining: 790ms
181:	learn: 0.3962077	total: 176ms	remaining: 790ms
182:	learn: 0.3958261	total: 177ms	remaining: 790ms
183:	learn: 0.3953001	total: 178ms	remaining: 790ms
184:	learn: 0.3945768	total: 179ms	remaining: 790ms
185:	learn: 0.3944490	total: 180ms	remaining: 788ms
186:	learn: 0.3942635	total: 181ms	remaining: 789ms
187:	learn: 

333:	learn: 0.3591062	total: 331ms	remaining: 661ms
334:	learn: 0.3587415	total: 333ms	remaining: 660ms
335:	learn: 0.3585527	total: 334ms	remaining: 659ms
336:	learn: 0.3583495	total: 335ms	remaining: 659ms
337:	learn: 0.3581226	total: 336ms	remaining: 658ms
338:	learn: 0.3578042	total: 337ms	remaining: 657ms
339:	learn: 0.3577081	total: 338ms	remaining: 656ms
340:	learn: 0.3574515	total: 339ms	remaining: 656ms
341:	learn: 0.3572917	total: 340ms	remaining: 655ms
342:	learn: 0.3570493	total: 342ms	remaining: 655ms
343:	learn: 0.3567966	total: 343ms	remaining: 654ms
344:	learn: 0.3566420	total: 344ms	remaining: 653ms
345:	learn: 0.3564939	total: 345ms	remaining: 653ms
346:	learn: 0.3562813	total: 346ms	remaining: 652ms
347:	learn: 0.3561165	total: 348ms	remaining: 652ms
348:	learn: 0.3560916	total: 348ms	remaining: 650ms
349:	learn: 0.3560858	total: 349ms	remaining: 648ms
350:	learn: 0.3558542	total: 350ms	remaining: 647ms
351:	learn: 0.3556278	total: 351ms	remaining: 646ms
352:	learn: 

503:	learn: 0.3345903	total: 501ms	remaining: 493ms
504:	learn: 0.3345624	total: 502ms	remaining: 492ms
505:	learn: 0.3342005	total: 503ms	remaining: 492ms
506:	learn: 0.3341361	total: 505ms	remaining: 491ms
507:	learn: 0.3339709	total: 506ms	remaining: 490ms
508:	learn: 0.3338157	total: 507ms	remaining: 489ms
509:	learn: 0.3336303	total: 508ms	remaining: 488ms
510:	learn: 0.3336288	total: 508ms	remaining: 486ms
511:	learn: 0.3335630	total: 509ms	remaining: 485ms
512:	learn: 0.3334902	total: 510ms	remaining: 484ms
513:	learn: 0.3333991	total: 511ms	remaining: 484ms
514:	learn: 0.3333391	total: 513ms	remaining: 483ms
515:	learn: 0.3331326	total: 514ms	remaining: 482ms
516:	learn: 0.3330350	total: 515ms	remaining: 481ms
517:	learn: 0.3329743	total: 516ms	remaining: 480ms
518:	learn: 0.3327169	total: 517ms	remaining: 479ms
519:	learn: 0.3324185	total: 518ms	remaining: 478ms
520:	learn: 0.3322674	total: 519ms	remaining: 477ms
521:	learn: 0.3320956	total: 520ms	remaining: 476ms
522:	learn: 

672:	learn: 0.3147681	total: 672ms	remaining: 326ms
673:	learn: 0.3146507	total: 673ms	remaining: 326ms
674:	learn: 0.3146042	total: 674ms	remaining: 325ms
675:	learn: 0.3144357	total: 675ms	remaining: 324ms
676:	learn: 0.3144123	total: 676ms	remaining: 322ms
677:	learn: 0.3143315	total: 677ms	remaining: 322ms
678:	learn: 0.3142206	total: 678ms	remaining: 321ms
679:	learn: 0.3142003	total: 679ms	remaining: 320ms
680:	learn: 0.3141100	total: 680ms	remaining: 319ms
681:	learn: 0.3140218	total: 681ms	remaining: 318ms
682:	learn: 0.3138726	total: 682ms	remaining: 317ms
683:	learn: 0.3138154	total: 684ms	remaining: 316ms
684:	learn: 0.3136750	total: 685ms	remaining: 315ms
685:	learn: 0.3136676	total: 685ms	remaining: 314ms
686:	learn: 0.3135778	total: 686ms	remaining: 313ms
687:	learn: 0.3134132	total: 687ms	remaining: 312ms
688:	learn: 0.3133610	total: 688ms	remaining: 311ms
689:	learn: 0.3131636	total: 689ms	remaining: 310ms
690:	learn: 0.3130921	total: 690ms	remaining: 309ms
691:	learn: 

843:	learn: 0.2949840	total: 842ms	remaining: 156ms
844:	learn: 0.2949440	total: 844ms	remaining: 155ms
845:	learn: 0.2947969	total: 845ms	remaining: 154ms
846:	learn: 0.2946791	total: 846ms	remaining: 153ms
847:	learn: 0.2944231	total: 847ms	remaining: 152ms
848:	learn: 0.2944182	total: 847ms	remaining: 151ms
849:	learn: 0.2943213	total: 848ms	remaining: 150ms
850:	learn: 0.2942622	total: 849ms	remaining: 149ms
851:	learn: 0.2941172	total: 850ms	remaining: 148ms
852:	learn: 0.2938485	total: 851ms	remaining: 147ms
853:	learn: 0.2937804	total: 852ms	remaining: 146ms
854:	learn: 0.2937479	total: 853ms	remaining: 145ms
855:	learn: 0.2936317	total: 854ms	remaining: 144ms
856:	learn: 0.2933686	total: 855ms	remaining: 143ms
857:	learn: 0.2932475	total: 856ms	remaining: 142ms
858:	learn: 0.2931171	total: 857ms	remaining: 141ms
859:	learn: 0.2928650	total: 858ms	remaining: 140ms
860:	learn: 0.2927830	total: 859ms	remaining: 139ms
861:	learn: 0.2926828	total: 861ms	remaining: 138ms
862:	learn: 

0:	learn: 0.6869575	total: 16.6ms	remaining: 16.6s
1:	learn: 0.6836075	total: 17.4ms	remaining: 8.67s
2:	learn: 0.6781949	total: 18.5ms	remaining: 6.14s
3:	learn: 0.6727492	total: 19.6ms	remaining: 4.87s
4:	learn: 0.6671685	total: 20.6ms	remaining: 4.11s
5:	learn: 0.6623728	total: 21.7ms	remaining: 3.6s
6:	learn: 0.6583624	total: 22.5ms	remaining: 3.19s
7:	learn: 0.6529436	total: 23.6ms	remaining: 2.92s
8:	learn: 0.6479676	total: 24.8ms	remaining: 2.73s
9:	learn: 0.6428288	total: 25.6ms	remaining: 2.54s
10:	learn: 0.6374700	total: 26.6ms	remaining: 2.39s
11:	learn: 0.6321587	total: 27.6ms	remaining: 2.27s
12:	learn: 0.6275448	total: 28.6ms	remaining: 2.17s
13:	learn: 0.6232602	total: 29.5ms	remaining: 2.08s
14:	learn: 0.6188018	total: 30.1ms	remaining: 1.98s
15:	learn: 0.6138587	total: 31.1ms	remaining: 1.91s
16:	learn: 0.6093959	total: 32ms	remaining: 1.85s
17:	learn: 0.6050745	total: 33ms	remaining: 1.8s
18:	learn: 0.6009635	total: 33.7ms	remaining: 1.74s
19:	learn: 0.5968292	total: 

171:	learn: 0.3863528	total: 181ms	remaining: 870ms
172:	learn: 0.3856626	total: 182ms	remaining: 870ms
173:	learn: 0.3853263	total: 183ms	remaining: 869ms
174:	learn: 0.3846522	total: 184ms	remaining: 869ms
175:	learn: 0.3844062	total: 185ms	remaining: 867ms
176:	learn: 0.3839993	total: 186ms	remaining: 867ms
177:	learn: 0.3835668	total: 188ms	remaining: 866ms
178:	learn: 0.3832470	total: 189ms	remaining: 865ms
179:	learn: 0.3828568	total: 190ms	remaining: 865ms
180:	learn: 0.3826264	total: 191ms	remaining: 865ms
181:	learn: 0.3823727	total: 192ms	remaining: 864ms
182:	learn: 0.3820144	total: 194ms	remaining: 864ms
183:	learn: 0.3815460	total: 195ms	remaining: 864ms
184:	learn: 0.3811855	total: 196ms	remaining: 863ms
185:	learn: 0.3806233	total: 197ms	remaining: 862ms
186:	learn: 0.3803053	total: 198ms	remaining: 860ms
187:	learn: 0.3799849	total: 199ms	remaining: 859ms
188:	learn: 0.3795492	total: 200ms	remaining: 858ms
189:	learn: 0.3791837	total: 201ms	remaining: 857ms
190:	learn: 

339:	learn: 0.3467596	total: 350ms	remaining: 680ms
340:	learn: 0.3466955	total: 352ms	remaining: 680ms
341:	learn: 0.3464235	total: 353ms	remaining: 679ms
342:	learn: 0.3461998	total: 354ms	remaining: 678ms
343:	learn: 0.3461260	total: 355ms	remaining: 677ms
344:	learn: 0.3460086	total: 356ms	remaining: 676ms
345:	learn: 0.3459420	total: 357ms	remaining: 675ms
346:	learn: 0.3457918	total: 358ms	remaining: 674ms
347:	learn: 0.3457016	total: 359ms	remaining: 673ms
348:	learn: 0.3455394	total: 361ms	remaining: 672ms
349:	learn: 0.3455353	total: 361ms	remaining: 671ms
350:	learn: 0.3454434	total: 362ms	remaining: 670ms
351:	learn: 0.3452927	total: 363ms	remaining: 669ms
352:	learn: 0.3452507	total: 364ms	remaining: 668ms
353:	learn: 0.3451219	total: 365ms	remaining: 667ms
354:	learn: 0.3449996	total: 366ms	remaining: 666ms
355:	learn: 0.3448947	total: 367ms	remaining: 665ms
356:	learn: 0.3447689	total: 368ms	remaining: 663ms
357:	learn: 0.3445393	total: 369ms	remaining: 662ms
358:	learn: 

503:	learn: 0.3268770	total: 519ms	remaining: 511ms
504:	learn: 0.3267767	total: 520ms	remaining: 510ms
505:	learn: 0.3267454	total: 521ms	remaining: 509ms
506:	learn: 0.3266575	total: 523ms	remaining: 508ms
507:	learn: 0.3265233	total: 524ms	remaining: 507ms
508:	learn: 0.3263014	total: 525ms	remaining: 506ms
509:	learn: 0.3262581	total: 525ms	remaining: 505ms
510:	learn: 0.3262360	total: 527ms	remaining: 504ms
511:	learn: 0.3261291	total: 528ms	remaining: 503ms
512:	learn: 0.3259626	total: 529ms	remaining: 502ms
513:	learn: 0.3258514	total: 530ms	remaining: 501ms
514:	learn: 0.3256753	total: 531ms	remaining: 500ms
515:	learn: 0.3256634	total: 532ms	remaining: 499ms
516:	learn: 0.3256023	total: 533ms	remaining: 498ms
517:	learn: 0.3254704	total: 534ms	remaining: 497ms
518:	learn: 0.3253900	total: 535ms	remaining: 496ms
519:	learn: 0.3252018	total: 537ms	remaining: 495ms
520:	learn: 0.3250299	total: 538ms	remaining: 494ms
521:	learn: 0.3249835	total: 539ms	remaining: 493ms
522:	learn: 

808:	learn: 0.2932030	total: 853ms	remaining: 201ms
809:	learn: 0.2931144	total: 854ms	remaining: 200ms
810:	learn: 0.2930578	total: 855ms	remaining: 199ms
811:	learn: 0.2929055	total: 857ms	remaining: 198ms
812:	learn: 0.2928755	total: 858ms	remaining: 197ms
813:	learn: 0.2927419	total: 859ms	remaining: 196ms
814:	learn: 0.2926214	total: 860ms	remaining: 195ms
815:	learn: 0.2924700	total: 861ms	remaining: 194ms
816:	learn: 0.2924131	total: 862ms	remaining: 193ms
817:	learn: 0.2923673	total: 863ms	remaining: 192ms
818:	learn: 0.2922400	total: 864ms	remaining: 191ms
819:	learn: 0.2921560	total: 865ms	remaining: 190ms
820:	learn: 0.2920912	total: 866ms	remaining: 189ms
821:	learn: 0.2920020	total: 867ms	remaining: 188ms
822:	learn: 0.2919151	total: 868ms	remaining: 187ms
823:	learn: 0.2918006	total: 869ms	remaining: 186ms
824:	learn: 0.2917138	total: 870ms	remaining: 184ms
825:	learn: 0.2915543	total: 871ms	remaining: 183ms
826:	learn: 0.2914800	total: 872ms	remaining: 182ms
827:	learn: 

970:	learn: 0.2749207	total: 1.02s	remaining: 30.5ms
971:	learn: 0.2748874	total: 1.02s	remaining: 29.5ms
972:	learn: 0.2747677	total: 1.02s	remaining: 28.4ms
973:	learn: 0.2746401	total: 1.02s	remaining: 27.4ms
974:	learn: 0.2745443	total: 1.02s	remaining: 26.3ms
975:	learn: 0.2744535	total: 1.03s	remaining: 25.3ms
976:	learn: 0.2743624	total: 1.03s	remaining: 24.2ms
977:	learn: 0.2742705	total: 1.03s	remaining: 23.2ms
978:	learn: 0.2742106	total: 1.03s	remaining: 22.1ms
979:	learn: 0.2740870	total: 1.03s	remaining: 21ms
980:	learn: 0.2738144	total: 1.03s	remaining: 20ms
981:	learn: 0.2737516	total: 1.03s	remaining: 18.9ms
982:	learn: 0.2737367	total: 1.03s	remaining: 17.9ms
983:	learn: 0.2736536	total: 1.04s	remaining: 16.8ms
984:	learn: 0.2735316	total: 1.04s	remaining: 15.8ms
985:	learn: 0.2734046	total: 1.04s	remaining: 14.7ms
986:	learn: 0.2732526	total: 1.04s	remaining: 13.7ms
987:	learn: 0.2731747	total: 1.04s	remaining: 12.6ms
988:	learn: 0.2730277	total: 1.04s	remaining: 11.6

290:	learn: 0.3421576	total: 282ms	remaining: 687ms
291:	learn: 0.3420026	total: 283ms	remaining: 686ms
292:	learn: 0.3419117	total: 284ms	remaining: 686ms
293:	learn: 0.3416047	total: 285ms	remaining: 685ms
294:	learn: 0.3414481	total: 286ms	remaining: 684ms
295:	learn: 0.3411950	total: 287ms	remaining: 684ms
296:	learn: 0.3410316	total: 288ms	remaining: 683ms
297:	learn: 0.3409632	total: 290ms	remaining: 682ms
298:	learn: 0.3407140	total: 291ms	remaining: 682ms
299:	learn: 0.3405153	total: 292ms	remaining: 681ms
300:	learn: 0.3403486	total: 293ms	remaining: 680ms
301:	learn: 0.3403154	total: 294ms	remaining: 679ms
302:	learn: 0.3400629	total: 295ms	remaining: 678ms
303:	learn: 0.3398732	total: 296ms	remaining: 678ms
304:	learn: 0.3398057	total: 297ms	remaining: 677ms
305:	learn: 0.3395821	total: 298ms	remaining: 676ms
306:	learn: 0.3394760	total: 299ms	remaining: 675ms
307:	learn: 0.3394150	total: 300ms	remaining: 674ms
308:	learn: 0.3391366	total: 301ms	remaining: 673ms
309:	learn: 

451:	learn: 0.3193014	total: 450ms	remaining: 546ms
452:	learn: 0.3192408	total: 452ms	remaining: 545ms
453:	learn: 0.3190991	total: 453ms	remaining: 544ms
454:	learn: 0.3189521	total: 454ms	remaining: 543ms
455:	learn: 0.3187608	total: 455ms	remaining: 542ms
456:	learn: 0.3186293	total: 456ms	remaining: 541ms
457:	learn: 0.3183569	total: 457ms	remaining: 540ms
458:	learn: 0.3182744	total: 458ms	remaining: 539ms
459:	learn: 0.3180783	total: 459ms	remaining: 539ms
460:	learn: 0.3180540	total: 459ms	remaining: 537ms
461:	learn: 0.3180005	total: 461ms	remaining: 536ms
462:	learn: 0.3178359	total: 462ms	remaining: 536ms
463:	learn: 0.3177539	total: 463ms	remaining: 535ms
464:	learn: 0.3177235	total: 464ms	remaining: 534ms
465:	learn: 0.3176610	total: 465ms	remaining: 533ms
466:	learn: 0.3175139	total: 466ms	remaining: 532ms
467:	learn: 0.3174240	total: 467ms	remaining: 531ms
468:	learn: 0.3172987	total: 468ms	remaining: 530ms
469:	learn: 0.3171165	total: 469ms	remaining: 529ms
470:	learn: 

618:	learn: 0.3022989	total: 619ms	remaining: 381ms
619:	learn: 0.3021286	total: 620ms	remaining: 380ms
620:	learn: 0.3020544	total: 621ms	remaining: 379ms
621:	learn: 0.3019392	total: 622ms	remaining: 378ms
622:	learn: 0.3017789	total: 623ms	remaining: 377ms
623:	learn: 0.3017072	total: 624ms	remaining: 376ms
624:	learn: 0.3016592	total: 625ms	remaining: 375ms
625:	learn: 0.3015938	total: 626ms	remaining: 374ms
626:	learn: 0.3014627	total: 627ms	remaining: 373ms
627:	learn: 0.3012725	total: 628ms	remaining: 372ms
628:	learn: 0.3012194	total: 629ms	remaining: 371ms
629:	learn: 0.3011864	total: 630ms	remaining: 370ms
630:	learn: 0.3011633	total: 631ms	remaining: 369ms
631:	learn: 0.3011172	total: 632ms	remaining: 368ms
632:	learn: 0.3009760	total: 633ms	remaining: 367ms
633:	learn: 0.3008737	total: 634ms	remaining: 366ms
634:	learn: 0.3008318	total: 636ms	remaining: 365ms
635:	learn: 0.3005816	total: 637ms	remaining: 364ms
636:	learn: 0.3003892	total: 638ms	remaining: 363ms
637:	learn: 

783:	learn: 0.2827132	total: 789ms	remaining: 217ms
784:	learn: 0.2826111	total: 791ms	remaining: 217ms
785:	learn: 0.2824259	total: 792ms	remaining: 216ms
786:	learn: 0.2823440	total: 793ms	remaining: 215ms
787:	learn: 0.2822062	total: 794ms	remaining: 214ms
788:	learn: 0.2820532	total: 795ms	remaining: 213ms
789:	learn: 0.2818032	total: 796ms	remaining: 212ms
790:	learn: 0.2817029	total: 797ms	remaining: 211ms
791:	learn: 0.2816835	total: 798ms	remaining: 210ms
792:	learn: 0.2816300	total: 800ms	remaining: 209ms
793:	learn: 0.2815652	total: 801ms	remaining: 208ms
794:	learn: 0.2814680	total: 802ms	remaining: 207ms
795:	learn: 0.2813714	total: 803ms	remaining: 206ms
796:	learn: 0.2812301	total: 804ms	remaining: 205ms
797:	learn: 0.2811360	total: 805ms	remaining: 204ms
798:	learn: 0.2809486	total: 806ms	remaining: 203ms
799:	learn: 0.2807501	total: 807ms	remaining: 202ms
800:	learn: 0.2805851	total: 809ms	remaining: 201ms
801:	learn: 0.2804072	total: 810ms	remaining: 200ms
802:	learn: 

946:	learn: 0.2612589	total: 960ms	remaining: 53.7ms
947:	learn: 0.2611791	total: 961ms	remaining: 52.7ms
948:	learn: 0.2610767	total: 962ms	remaining: 51.7ms
949:	learn: 0.2610095	total: 963ms	remaining: 50.7ms
950:	learn: 0.2607939	total: 964ms	remaining: 49.7ms
951:	learn: 0.2606681	total: 966ms	remaining: 48.7ms
952:	learn: 0.2605792	total: 967ms	remaining: 47.7ms
953:	learn: 0.2605312	total: 968ms	remaining: 46.7ms
954:	learn: 0.2603381	total: 969ms	remaining: 45.7ms
955:	learn: 0.2603095	total: 970ms	remaining: 44.6ms
956:	learn: 0.2602052	total: 971ms	remaining: 43.6ms
957:	learn: 0.2601050	total: 973ms	remaining: 42.6ms
958:	learn: 0.2599621	total: 974ms	remaining: 41.6ms
959:	learn: 0.2598438	total: 975ms	remaining: 40.6ms
960:	learn: 0.2595494	total: 976ms	remaining: 39.6ms
961:	learn: 0.2593987	total: 977ms	remaining: 38.6ms
962:	learn: 0.2593353	total: 978ms	remaining: 37.6ms
963:	learn: 0.2592950	total: 979ms	remaining: 36.6ms
964:	learn: 0.2590973	total: 980ms	remaining: 

254:	learn: 0.3887527	total: 252ms	remaining: 736ms
255:	learn: 0.3884959	total: 253ms	remaining: 736ms
256:	learn: 0.3883602	total: 254ms	remaining: 735ms
257:	learn: 0.3881705	total: 255ms	remaining: 734ms
258:	learn: 0.3880624	total: 256ms	remaining: 733ms
259:	learn: 0.3878788	total: 257ms	remaining: 732ms
260:	learn: 0.3875960	total: 258ms	remaining: 731ms
261:	learn: 0.3872743	total: 259ms	remaining: 731ms
262:	learn: 0.3870186	total: 260ms	remaining: 730ms
263:	learn: 0.3868149	total: 261ms	remaining: 729ms
264:	learn: 0.3867165	total: 263ms	remaining: 728ms
265:	learn: 0.3864937	total: 264ms	remaining: 728ms
266:	learn: 0.3863255	total: 265ms	remaining: 727ms
267:	learn: 0.3861548	total: 266ms	remaining: 726ms
268:	learn: 0.3857739	total: 267ms	remaining: 725ms
269:	learn: 0.3856782	total: 268ms	remaining: 724ms
270:	learn: 0.3856628	total: 268ms	remaining: 722ms
271:	learn: 0.3855414	total: 269ms	remaining: 721ms
272:	learn: 0.3852380	total: 270ms	remaining: 720ms
273:	learn: 

421:	learn: 0.3599144	total: 423ms	remaining: 579ms
422:	learn: 0.3597465	total: 424ms	remaining: 578ms
423:	learn: 0.3595649	total: 425ms	remaining: 578ms
424:	learn: 0.3594675	total: 426ms	remaining: 577ms
425:	learn: 0.3594603	total: 427ms	remaining: 575ms
426:	learn: 0.3592772	total: 428ms	remaining: 574ms
427:	learn: 0.3591264	total: 429ms	remaining: 573ms
428:	learn: 0.3589567	total: 430ms	remaining: 572ms
429:	learn: 0.3588881	total: 431ms	remaining: 571ms
430:	learn: 0.3588461	total: 432ms	remaining: 570ms
431:	learn: 0.3587629	total: 433ms	remaining: 569ms
432:	learn: 0.3586835	total: 434ms	remaining: 569ms
433:	learn: 0.3584927	total: 435ms	remaining: 568ms
434:	learn: 0.3584440	total: 437ms	remaining: 567ms
435:	learn: 0.3581123	total: 437ms	remaining: 566ms
436:	learn: 0.3580576	total: 438ms	remaining: 565ms
437:	learn: 0.3580099	total: 439ms	remaining: 564ms
438:	learn: 0.3579025	total: 440ms	remaining: 563ms
439:	learn: 0.3578171	total: 441ms	remaining: 562ms
440:	learn: 

727:	learn: 0.3247002	total: 755ms	remaining: 282ms
728:	learn: 0.3246279	total: 756ms	remaining: 281ms
729:	learn: 0.3244668	total: 758ms	remaining: 280ms
730:	learn: 0.3242982	total: 759ms	remaining: 279ms
731:	learn: 0.3240697	total: 760ms	remaining: 278ms
732:	learn: 0.3237685	total: 761ms	remaining: 277ms
733:	learn: 0.3236878	total: 762ms	remaining: 276ms
734:	learn: 0.3235246	total: 763ms	remaining: 275ms
735:	learn: 0.3234786	total: 764ms	remaining: 274ms
736:	learn: 0.3233621	total: 765ms	remaining: 273ms
737:	learn: 0.3233442	total: 766ms	remaining: 272ms
738:	learn: 0.3232626	total: 767ms	remaining: 271ms
739:	learn: 0.3230664	total: 768ms	remaining: 270ms
740:	learn: 0.3228576	total: 769ms	remaining: 269ms
741:	learn: 0.3227511	total: 770ms	remaining: 268ms
742:	learn: 0.3225878	total: 772ms	remaining: 267ms
743:	learn: 0.3225700	total: 772ms	remaining: 266ms
744:	learn: 0.3224524	total: 774ms	remaining: 265ms
745:	learn: 0.3223328	total: 775ms	remaining: 264ms
746:	learn: 

887:	learn: 0.3072350	total: 924ms	remaining: 117ms
888:	learn: 0.3071485	total: 925ms	remaining: 116ms
889:	learn: 0.3070278	total: 926ms	remaining: 114ms
890:	learn: 0.3068753	total: 927ms	remaining: 113ms
891:	learn: 0.3067601	total: 928ms	remaining: 112ms
892:	learn: 0.3066798	total: 930ms	remaining: 111ms
893:	learn: 0.3066361	total: 931ms	remaining: 110ms
894:	learn: 0.3064612	total: 932ms	remaining: 109ms
895:	learn: 0.3063008	total: 933ms	remaining: 108ms
896:	learn: 0.3060668	total: 934ms	remaining: 107ms
897:	learn: 0.3059770	total: 935ms	remaining: 106ms
898:	learn: 0.3058768	total: 936ms	remaining: 105ms
899:	learn: 0.3056551	total: 938ms	remaining: 104ms
900:	learn: 0.3055823	total: 939ms	remaining: 103ms
901:	learn: 0.3054815	total: 940ms	remaining: 102ms
902:	learn: 0.3052921	total: 941ms	remaining: 101ms
903:	learn: 0.3051624	total: 942ms	remaining: 100ms
904:	learn: 0.3050485	total: 944ms	remaining: 99.1ms
905:	learn: 0.3050046	total: 945ms	remaining: 98ms
906:	learn: 

188:	learn: 0.3941148	total: 189ms	remaining: 811ms
189:	learn: 0.3937657	total: 190ms	remaining: 810ms
190:	learn: 0.3934182	total: 192ms	remaining: 811ms
191:	learn: 0.3930145	total: 193ms	remaining: 811ms
192:	learn: 0.3927664	total: 194ms	remaining: 810ms
193:	learn: 0.3923941	total: 195ms	remaining: 809ms
194:	learn: 0.3919888	total: 196ms	remaining: 809ms
195:	learn: 0.3917079	total: 197ms	remaining: 808ms
196:	learn: 0.3914003	total: 198ms	remaining: 808ms
197:	learn: 0.3912743	total: 199ms	remaining: 806ms
198:	learn: 0.3911545	total: 200ms	remaining: 804ms
199:	learn: 0.3908853	total: 201ms	remaining: 804ms
200:	learn: 0.3905226	total: 202ms	remaining: 803ms
201:	learn: 0.3901147	total: 203ms	remaining: 803ms
202:	learn: 0.3897798	total: 204ms	remaining: 802ms
203:	learn: 0.3895234	total: 206ms	remaining: 803ms
204:	learn: 0.3892565	total: 207ms	remaining: 802ms
205:	learn: 0.3891335	total: 208ms	remaining: 801ms
206:	learn: 0.3888779	total: 209ms	remaining: 800ms
207:	learn: 

358:	learn: 0.3592564	total: 359ms	remaining: 640ms
359:	learn: 0.3592392	total: 359ms	remaining: 639ms
360:	learn: 0.3590480	total: 360ms	remaining: 638ms
361:	learn: 0.3589767	total: 362ms	remaining: 637ms
362:	learn: 0.3586923	total: 363ms	remaining: 636ms
363:	learn: 0.3586112	total: 364ms	remaining: 635ms
364:	learn: 0.3585416	total: 365ms	remaining: 634ms
365:	learn: 0.3585179	total: 365ms	remaining: 633ms
366:	learn: 0.3584406	total: 367ms	remaining: 632ms
367:	learn: 0.3582015	total: 368ms	remaining: 632ms
368:	learn: 0.3581280	total: 369ms	remaining: 631ms
369:	learn: 0.3580994	total: 370ms	remaining: 629ms
370:	learn: 0.3580610	total: 371ms	remaining: 629ms
371:	learn: 0.3580115	total: 373ms	remaining: 629ms
372:	learn: 0.3577824	total: 374ms	remaining: 628ms
373:	learn: 0.3576726	total: 375ms	remaining: 628ms
374:	learn: 0.3574878	total: 376ms	remaining: 627ms
375:	learn: 0.3574242	total: 377ms	remaining: 626ms
376:	learn: 0.3572103	total: 378ms	remaining: 625ms
377:	learn: 

518:	learn: 0.3389193	total: 527ms	remaining: 488ms
519:	learn: 0.3388482	total: 528ms	remaining: 487ms
520:	learn: 0.3386956	total: 529ms	remaining: 487ms
521:	learn: 0.3385740	total: 530ms	remaining: 486ms
522:	learn: 0.3385588	total: 531ms	remaining: 484ms
523:	learn: 0.3384903	total: 532ms	remaining: 483ms
524:	learn: 0.3384245	total: 533ms	remaining: 482ms
525:	learn: 0.3383874	total: 534ms	remaining: 481ms
526:	learn: 0.3382428	total: 535ms	remaining: 480ms
527:	learn: 0.3380803	total: 536ms	remaining: 479ms
528:	learn: 0.3379694	total: 537ms	remaining: 479ms
529:	learn: 0.3378471	total: 539ms	remaining: 478ms
530:	learn: 0.3375602	total: 540ms	remaining: 477ms
531:	learn: 0.3374957	total: 541ms	remaining: 476ms
532:	learn: 0.3374039	total: 542ms	remaining: 475ms
533:	learn: 0.3373816	total: 543ms	remaining: 474ms
534:	learn: 0.3373573	total: 544ms	remaining: 473ms
535:	learn: 0.3372241	total: 545ms	remaining: 472ms
536:	learn: 0.3372109	total: 545ms	remaining: 470ms
537:	learn: 

682:	learn: 0.3210037	total: 696ms	remaining: 323ms
683:	learn: 0.3209337	total: 697ms	remaining: 322ms
684:	learn: 0.3208592	total: 698ms	remaining: 321ms
685:	learn: 0.3207167	total: 699ms	remaining: 320ms
686:	learn: 0.3207058	total: 700ms	remaining: 319ms
687:	learn: 0.3206563	total: 701ms	remaining: 318ms
688:	learn: 0.3204716	total: 703ms	remaining: 317ms
689:	learn: 0.3203958	total: 704ms	remaining: 316ms
690:	learn: 0.3203294	total: 705ms	remaining: 315ms
691:	learn: 0.3202611	total: 706ms	remaining: 314ms
692:	learn: 0.3201920	total: 707ms	remaining: 313ms
693:	learn: 0.3201357	total: 708ms	remaining: 312ms
694:	learn: 0.3199327	total: 709ms	remaining: 311ms
695:	learn: 0.3198229	total: 710ms	remaining: 310ms
696:	learn: 0.3196913	total: 711ms	remaining: 309ms
697:	learn: 0.3195649	total: 712ms	remaining: 308ms
698:	learn: 0.3193601	total: 714ms	remaining: 307ms
699:	learn: 0.3192988	total: 715ms	remaining: 306ms
700:	learn: 0.3192362	total: 716ms	remaining: 305ms
701:	learn: 

989:	learn: 0.2857613	total: 1.03s	remaining: 10.4ms
990:	learn: 0.2857007	total: 1.03s	remaining: 9.38ms
991:	learn: 0.2856062	total: 1.03s	remaining: 8.34ms
992:	learn: 0.2854839	total: 1.03s	remaining: 7.3ms
993:	learn: 0.2853853	total: 1.04s	remaining: 6.25ms
994:	learn: 0.2853489	total: 1.04s	remaining: 5.21ms
995:	learn: 0.2852473	total: 1.04s	remaining: 4.17ms
996:	learn: 0.2852033	total: 1.04s	remaining: 3.13ms
997:	learn: 0.2850907	total: 1.04s	remaining: 2.08ms
998:	learn: 0.2849569	total: 1.04s	remaining: 1.04ms
999:	learn: 0.2848792	total: 1.04s	remaining: 0us
Learning rate set to 0.00852
0:	learn: 0.6872034	total: 1.21ms	remaining: 1.21s
1:	learn: 0.6836602	total: 1.84ms	remaining: 919ms
2:	learn: 0.6796306	total: 3.44ms	remaining: 1.14s
3:	learn: 0.6748088	total: 4.67ms	remaining: 1.16s
4:	learn: 0.6683630	total: 5.88ms	remaining: 1.17s
5:	learn: 0.6637160	total: 7.07ms	remaining: 1.17s
6:	learn: 0.6576700	total: 8.18ms	remaining: 1.16s
7:	learn: 0.6521921	total: 9.39ms	r

244:	learn: 0.3609822	total: 294ms	remaining: 905ms
245:	learn: 0.3608749	total: 295ms	remaining: 904ms
246:	learn: 0.3606866	total: 296ms	remaining: 903ms
247:	learn: 0.3605184	total: 297ms	remaining: 902ms
248:	learn: 0.3601618	total: 299ms	remaining: 900ms
249:	learn: 0.3598557	total: 300ms	remaining: 899ms
250:	learn: 0.3595975	total: 301ms	remaining: 898ms
251:	learn: 0.3593701	total: 302ms	remaining: 896ms
252:	learn: 0.3590111	total: 303ms	remaining: 895ms
253:	learn: 0.3587019	total: 304ms	remaining: 894ms
254:	learn: 0.3584409	total: 306ms	remaining: 893ms
255:	learn: 0.3583845	total: 307ms	remaining: 891ms
256:	learn: 0.3580920	total: 308ms	remaining: 890ms
257:	learn: 0.3578606	total: 309ms	remaining: 890ms
258:	learn: 0.3575003	total: 311ms	remaining: 889ms
259:	learn: 0.3572856	total: 312ms	remaining: 887ms
260:	learn: 0.3570506	total: 313ms	remaining: 886ms
261:	learn: 0.3567290	total: 314ms	remaining: 885ms
262:	learn: 0.3565080	total: 316ms	remaining: 885ms
263:	learn: 

498:	learn: 0.3199201	total: 624ms	remaining: 626ms
499:	learn: 0.3197327	total: 625ms	remaining: 625ms
500:	learn: 0.3197091	total: 626ms	remaining: 624ms
501:	learn: 0.3195894	total: 628ms	remaining: 623ms
502:	learn: 0.3195505	total: 629ms	remaining: 621ms
503:	learn: 0.3194041	total: 630ms	remaining: 620ms
504:	learn: 0.3192979	total: 631ms	remaining: 618ms
505:	learn: 0.3192193	total: 632ms	remaining: 617ms
506:	learn: 0.3191041	total: 641ms	remaining: 624ms
507:	learn: 0.3190044	total: 643ms	remaining: 622ms
508:	learn: 0.3189586	total: 644ms	remaining: 621ms
509:	learn: 0.3186960	total: 645ms	remaining: 620ms
510:	learn: 0.3186210	total: 646ms	remaining: 619ms
511:	learn: 0.3183904	total: 648ms	remaining: 617ms
512:	learn: 0.3183211	total: 649ms	remaining: 616ms
513:	learn: 0.3182736	total: 650ms	remaining: 615ms
514:	learn: 0.3181214	total: 652ms	remaining: 614ms
515:	learn: 0.3180603	total: 654ms	remaining: 613ms
516:	learn: 0.3178901	total: 655ms	remaining: 612ms
517:	learn: 

777:	learn: 0.2861617	total: 957ms	remaining: 273ms
778:	learn: 0.2860646	total: 958ms	remaining: 272ms
779:	learn: 0.2859145	total: 959ms	remaining: 271ms
780:	learn: 0.2856799	total: 961ms	remaining: 269ms
781:	learn: 0.2854474	total: 962ms	remaining: 268ms
782:	learn: 0.2852442	total: 963ms	remaining: 267ms
783:	learn: 0.2851008	total: 964ms	remaining: 266ms
784:	learn: 0.2849315	total: 966ms	remaining: 264ms
785:	learn: 0.2848662	total: 967ms	remaining: 263ms
786:	learn: 0.2847922	total: 968ms	remaining: 262ms
787:	learn: 0.2846665	total: 969ms	remaining: 261ms
788:	learn: 0.2844640	total: 971ms	remaining: 260ms
789:	learn: 0.2841642	total: 972ms	remaining: 258ms
790:	learn: 0.2839898	total: 973ms	remaining: 257ms
791:	learn: 0.2838554	total: 974ms	remaining: 256ms
792:	learn: 0.2836678	total: 975ms	remaining: 255ms
793:	learn: 0.2835492	total: 977ms	remaining: 253ms
794:	learn: 0.2834770	total: 978ms	remaining: 252ms
795:	learn: 0.2833908	total: 979ms	remaining: 251ms
796:	learn: 

37:	learn: 0.5418452	total: 38.4ms	remaining: 973ms
38:	learn: 0.5388642	total: 39.7ms	remaining: 978ms
39:	learn: 0.5361775	total: 40.8ms	remaining: 978ms
40:	learn: 0.5333154	total: 41.8ms	remaining: 979ms
41:	learn: 0.5310470	total: 43ms	remaining: 980ms
42:	learn: 0.5286689	total: 44.1ms	remaining: 982ms
43:	learn: 0.5260333	total: 45.3ms	remaining: 984ms
44:	learn: 0.5233808	total: 46.4ms	remaining: 984ms
45:	learn: 0.5206383	total: 47.5ms	remaining: 985ms
46:	learn: 0.5181374	total: 48.6ms	remaining: 986ms
47:	learn: 0.5159701	total: 49.7ms	remaining: 985ms
48:	learn: 0.5135920	total: 50.7ms	remaining: 985ms
49:	learn: 0.5111359	total: 51.8ms	remaining: 983ms
50:	learn: 0.5085063	total: 52.9ms	remaining: 985ms
51:	learn: 0.5062612	total: 54.2ms	remaining: 988ms
52:	learn: 0.5040147	total: 55.4ms	remaining: 991ms
53:	learn: 0.5018810	total: 56.6ms	remaining: 992ms
54:	learn: 0.4999711	total: 57.7ms	remaining: 992ms
55:	learn: 0.4978524	total: 58.9ms	remaining: 992ms
56:	learn: 0.4

329:	learn: 0.3504953	total: 371ms	remaining: 752ms
330:	learn: 0.3503660	total: 372ms	remaining: 752ms
331:	learn: 0.3501163	total: 373ms	remaining: 751ms
332:	learn: 0.3500626	total: 374ms	remaining: 749ms
333:	learn: 0.3497957	total: 375ms	remaining: 748ms
334:	learn: 0.3496817	total: 376ms	remaining: 747ms
335:	learn: 0.3495082	total: 378ms	remaining: 746ms
336:	learn: 0.3492215	total: 379ms	remaining: 745ms
337:	learn: 0.3489527	total: 380ms	remaining: 744ms
338:	learn: 0.3488889	total: 381ms	remaining: 743ms
339:	learn: 0.3486913	total: 382ms	remaining: 742ms
340:	learn: 0.3486629	total: 383ms	remaining: 740ms
341:	learn: 0.3485304	total: 384ms	remaining: 739ms
342:	learn: 0.3484078	total: 385ms	remaining: 738ms
343:	learn: 0.3481464	total: 387ms	remaining: 738ms
344:	learn: 0.3480364	total: 388ms	remaining: 737ms
345:	learn: 0.3480305	total: 389ms	remaining: 735ms
346:	learn: 0.3479196	total: 390ms	remaining: 734ms
347:	learn: 0.3477786	total: 391ms	remaining: 732ms
348:	learn: 

638:	learn: 0.3123033	total: 705ms	remaining: 399ms
639:	learn: 0.3122103	total: 707ms	remaining: 398ms
640:	learn: 0.3120221	total: 708ms	remaining: 397ms
641:	learn: 0.3118573	total: 709ms	remaining: 396ms
642:	learn: 0.3117442	total: 710ms	remaining: 394ms
643:	learn: 0.3116099	total: 712ms	remaining: 393ms
644:	learn: 0.3113875	total: 713ms	remaining: 392ms
645:	learn: 0.3112432	total: 714ms	remaining: 391ms
646:	learn: 0.3111221	total: 715ms	remaining: 390ms
647:	learn: 0.3110529	total: 717ms	remaining: 389ms
648:	learn: 0.3109268	total: 718ms	remaining: 388ms
649:	learn: 0.3107017	total: 719ms	remaining: 387ms
650:	learn: 0.3105691	total: 721ms	remaining: 386ms
651:	learn: 0.3104430	total: 722ms	remaining: 385ms
652:	learn: 0.3102460	total: 724ms	remaining: 385ms
653:	learn: 0.3102009	total: 739ms	remaining: 391ms
654:	learn: 0.3101253	total: 741ms	remaining: 390ms
655:	learn: 0.3100272	total: 742ms	remaining: 389ms
656:	learn: 0.3098926	total: 744ms	remaining: 388ms
657:	learn: 

927:	learn: 0.2805902	total: 1.04s	remaining: 81ms
928:	learn: 0.2805389	total: 1.04s	remaining: 79.9ms
929:	learn: 0.2803022	total: 1.05s	remaining: 78.8ms
930:	learn: 0.2801623	total: 1.05s	remaining: 77.6ms
931:	learn: 0.2800456	total: 1.05s	remaining: 76.5ms
932:	learn: 0.2798999	total: 1.05s	remaining: 75.4ms
933:	learn: 0.2797806	total: 1.05s	remaining: 74.3ms
934:	learn: 0.2797058	total: 1.05s	remaining: 73.1ms
935:	learn: 0.2795862	total: 1.05s	remaining: 72ms
936:	learn: 0.2794421	total: 1.05s	remaining: 70.9ms
937:	learn: 0.2792976	total: 1.05s	remaining: 69.8ms
938:	learn: 0.2792294	total: 1.06s	remaining: 68.6ms
939:	learn: 0.2791541	total: 1.06s	remaining: 67.5ms
940:	learn: 0.2790268	total: 1.06s	remaining: 66.4ms
941:	learn: 0.2789064	total: 1.06s	remaining: 65.2ms
942:	learn: 0.2788630	total: 1.06s	remaining: 64.1ms
943:	learn: 0.2788421	total: 1.06s	remaining: 63ms
944:	learn: 0.2786973	total: 1.06s	remaining: 61.9ms
945:	learn: 0.2784435	total: 1.06s	remaining: 60.7ms

197:	learn: 0.3834888	total: 222ms	remaining: 898ms
198:	learn: 0.3831367	total: 223ms	remaining: 898ms
199:	learn: 0.3826966	total: 224ms	remaining: 897ms
200:	learn: 0.3823820	total: 225ms	remaining: 896ms
201:	learn: 0.3820655	total: 227ms	remaining: 895ms
202:	learn: 0.3817792	total: 228ms	remaining: 894ms
203:	learn: 0.3817033	total: 228ms	remaining: 891ms
204:	learn: 0.3814307	total: 230ms	remaining: 890ms
205:	learn: 0.3812311	total: 231ms	remaining: 889ms
206:	learn: 0.3811288	total: 231ms	remaining: 887ms
207:	learn: 0.3808682	total: 233ms	remaining: 887ms
208:	learn: 0.3805156	total: 234ms	remaining: 886ms
209:	learn: 0.3801117	total: 235ms	remaining: 885ms
210:	learn: 0.3799125	total: 237ms	remaining: 885ms
211:	learn: 0.3796380	total: 238ms	remaining: 885ms
212:	learn: 0.3795890	total: 239ms	remaining: 883ms
213:	learn: 0.3789994	total: 240ms	remaining: 882ms
214:	learn: 0.3786473	total: 241ms	remaining: 881ms
215:	learn: 0.3783154	total: 243ms	remaining: 881ms
216:	learn: 

506:	learn: 0.3326425	total: 557ms	remaining: 542ms
507:	learn: 0.3325487	total: 558ms	remaining: 541ms
508:	learn: 0.3323896	total: 559ms	remaining: 539ms
509:	learn: 0.3323508	total: 560ms	remaining: 538ms
510:	learn: 0.3323156	total: 561ms	remaining: 537ms
511:	learn: 0.3320808	total: 562ms	remaining: 536ms
512:	learn: 0.3318598	total: 563ms	remaining: 535ms
513:	learn: 0.3317444	total: 564ms	remaining: 534ms
514:	learn: 0.3316360	total: 565ms	remaining: 532ms
515:	learn: 0.3315013	total: 566ms	remaining: 531ms
516:	learn: 0.3314226	total: 568ms	remaining: 530ms
517:	learn: 0.3311698	total: 569ms	remaining: 529ms
518:	learn: 0.3309951	total: 570ms	remaining: 528ms
519:	learn: 0.3309138	total: 571ms	remaining: 527ms
520:	learn: 0.3308772	total: 572ms	remaining: 526ms
521:	learn: 0.3307955	total: 573ms	remaining: 524ms
522:	learn: 0.3307506	total: 574ms	remaining: 523ms
523:	learn: 0.3305748	total: 575ms	remaining: 522ms
524:	learn: 0.3304048	total: 576ms	remaining: 521ms
525:	learn: 

666:	learn: 0.3152740	total: 726ms	remaining: 362ms
667:	learn: 0.3152305	total: 727ms	remaining: 361ms
668:	learn: 0.3149086	total: 728ms	remaining: 360ms
669:	learn: 0.3148578	total: 730ms	remaining: 359ms
670:	learn: 0.3148538	total: 730ms	remaining: 358ms
671:	learn: 0.3147925	total: 731ms	remaining: 357ms
672:	learn: 0.3147611	total: 733ms	remaining: 356ms
673:	learn: 0.3146497	total: 734ms	remaining: 355ms
674:	learn: 0.3145033	total: 735ms	remaining: 354ms
675:	learn: 0.3144804	total: 735ms	remaining: 352ms
676:	learn: 0.3143250	total: 737ms	remaining: 351ms
677:	learn: 0.3142435	total: 738ms	remaining: 350ms
678:	learn: 0.3140073	total: 739ms	remaining: 349ms
679:	learn: 0.3138387	total: 740ms	remaining: 348ms
680:	learn: 0.3138054	total: 741ms	remaining: 347ms
681:	learn: 0.3136658	total: 743ms	remaining: 346ms
682:	learn: 0.3135794	total: 744ms	remaining: 345ms
683:	learn: 0.3133667	total: 745ms	remaining: 344ms
684:	learn: 0.3131486	total: 746ms	remaining: 343ms
685:	learn: 

829:	learn: 0.2980129	total: 897ms	remaining: 184ms
830:	learn: 0.2978931	total: 898ms	remaining: 183ms
831:	learn: 0.2977994	total: 899ms	remaining: 182ms
832:	learn: 0.2977337	total: 900ms	remaining: 180ms
833:	learn: 0.2976056	total: 901ms	remaining: 179ms
834:	learn: 0.2974265	total: 902ms	remaining: 178ms
835:	learn: 0.2973958	total: 903ms	remaining: 177ms
836:	learn: 0.2973248	total: 904ms	remaining: 176ms
837:	learn: 0.2972644	total: 905ms	remaining: 175ms
838:	learn: 0.2971655	total: 906ms	remaining: 174ms
839:	learn: 0.2970963	total: 907ms	remaining: 173ms
840:	learn: 0.2970700	total: 908ms	remaining: 172ms
841:	learn: 0.2969996	total: 909ms	remaining: 171ms
842:	learn: 0.2969646	total: 910ms	remaining: 170ms
843:	learn: 0.2967492	total: 911ms	remaining: 168ms
844:	learn: 0.2964671	total: 913ms	remaining: 167ms
845:	learn: 0.2963676	total: 914ms	remaining: 166ms
846:	learn: 0.2963264	total: 915ms	remaining: 165ms
847:	learn: 0.2962011	total: 916ms	remaining: 164ms
848:	learn: 

129:	learn: 0.3996785	total: 125ms	remaining: 837ms
130:	learn: 0.3992171	total: 126ms	remaining: 835ms
131:	learn: 0.3983513	total: 127ms	remaining: 834ms
132:	learn: 0.3975210	total: 128ms	remaining: 834ms
133:	learn: 0.3969324	total: 129ms	remaining: 833ms
134:	learn: 0.3964640	total: 130ms	remaining: 832ms
135:	learn: 0.3960716	total: 131ms	remaining: 829ms
136:	learn: 0.3956457	total: 132ms	remaining: 829ms
137:	learn: 0.3952231	total: 133ms	remaining: 828ms
138:	learn: 0.3948135	total: 133ms	remaining: 826ms
139:	learn: 0.3940897	total: 134ms	remaining: 826ms
140:	learn: 0.3934142	total: 135ms	remaining: 825ms
141:	learn: 0.3927112	total: 137ms	remaining: 825ms
142:	learn: 0.3921475	total: 138ms	remaining: 825ms
143:	learn: 0.3914331	total: 139ms	remaining: 824ms
144:	learn: 0.3908953	total: 140ms	remaining: 823ms
145:	learn: 0.3904064	total: 141ms	remaining: 823ms
146:	learn: 0.3900904	total: 141ms	remaining: 820ms
147:	learn: 0.3895204	total: 142ms	remaining: 820ms
148:	learn: 

297:	learn: 0.3475040	total: 293ms	remaining: 691ms
298:	learn: 0.3473734	total: 294ms	remaining: 690ms
299:	learn: 0.3471836	total: 295ms	remaining: 689ms
300:	learn: 0.3469256	total: 296ms	remaining: 688ms
301:	learn: 0.3466872	total: 297ms	remaining: 687ms
302:	learn: 0.3465295	total: 298ms	remaining: 686ms
303:	learn: 0.3464469	total: 300ms	remaining: 686ms
304:	learn: 0.3463489	total: 301ms	remaining: 685ms
305:	learn: 0.3460178	total: 302ms	remaining: 684ms
306:	learn: 0.3458043	total: 303ms	remaining: 684ms
307:	learn: 0.3456978	total: 304ms	remaining: 683ms
308:	learn: 0.3455772	total: 305ms	remaining: 682ms
309:	learn: 0.3455210	total: 306ms	remaining: 682ms
310:	learn: 0.3453825	total: 307ms	remaining: 681ms
311:	learn: 0.3452382	total: 309ms	remaining: 680ms
312:	learn: 0.3450759	total: 310ms	remaining: 680ms
313:	learn: 0.3448701	total: 311ms	remaining: 679ms
314:	learn: 0.3447698	total: 312ms	remaining: 678ms
315:	learn: 0.3446741	total: 313ms	remaining: 677ms
316:	learn: 

461:	learn: 0.3242818	total: 462ms	remaining: 538ms
462:	learn: 0.3241408	total: 463ms	remaining: 537ms
463:	learn: 0.3240676	total: 465ms	remaining: 537ms
464:	learn: 0.3240180	total: 466ms	remaining: 536ms
465:	learn: 0.3239471	total: 467ms	remaining: 535ms
466:	learn: 0.3238424	total: 468ms	remaining: 534ms
467:	learn: 0.3237161	total: 469ms	remaining: 533ms
468:	learn: 0.3235337	total: 470ms	remaining: 533ms
469:	learn: 0.3233766	total: 472ms	remaining: 532ms
470:	learn: 0.3232532	total: 473ms	remaining: 531ms
471:	learn: 0.3231711	total: 474ms	remaining: 530ms
472:	learn: 0.3231506	total: 475ms	remaining: 530ms
473:	learn: 0.3230418	total: 477ms	remaining: 529ms
474:	learn: 0.3228957	total: 478ms	remaining: 528ms
475:	learn: 0.3227958	total: 479ms	remaining: 528ms
476:	learn: 0.3226030	total: 480ms	remaining: 527ms
477:	learn: 0.3225673	total: 481ms	remaining: 525ms
478:	learn: 0.3225291	total: 482ms	remaining: 524ms
479:	learn: 0.3224751	total: 483ms	remaining: 523ms
480:	learn: 

628:	learn: 0.3070485	total: 632ms	remaining: 372ms
629:	learn: 0.3069746	total: 633ms	remaining: 372ms
630:	learn: 0.3069645	total: 634ms	remaining: 370ms
631:	learn: 0.3068437	total: 635ms	remaining: 369ms
632:	learn: 0.3067143	total: 636ms	remaining: 368ms
633:	learn: 0.3066537	total: 637ms	remaining: 367ms
634:	learn: 0.3064970	total: 637ms	remaining: 366ms
635:	learn: 0.3062891	total: 638ms	remaining: 365ms
636:	learn: 0.3061529	total: 639ms	remaining: 364ms
637:	learn: 0.3060431	total: 640ms	remaining: 363ms
638:	learn: 0.3059017	total: 641ms	remaining: 362ms
639:	learn: 0.3057422	total: 642ms	remaining: 361ms
640:	learn: 0.3056869	total: 644ms	remaining: 360ms
641:	learn: 0.3054722	total: 645ms	remaining: 360ms
642:	learn: 0.3053969	total: 646ms	remaining: 359ms
643:	learn: 0.3053191	total: 647ms	remaining: 358ms
644:	learn: 0.3052717	total: 648ms	remaining: 357ms
645:	learn: 0.3052038	total: 649ms	remaining: 356ms
646:	learn: 0.3051657	total: 650ms	remaining: 355ms
647:	learn: 

787:	learn: 0.2905799	total: 800ms	remaining: 215ms
788:	learn: 0.2905164	total: 801ms	remaining: 214ms
789:	learn: 0.2904555	total: 802ms	remaining: 213ms
790:	learn: 0.2903940	total: 803ms	remaining: 212ms
791:	learn: 0.2901054	total: 804ms	remaining: 211ms
792:	learn: 0.2900482	total: 805ms	remaining: 210ms
793:	learn: 0.2899879	total: 806ms	remaining: 209ms
794:	learn: 0.2899258	total: 807ms	remaining: 208ms
795:	learn: 0.2895748	total: 808ms	remaining: 207ms
796:	learn: 0.2894842	total: 809ms	remaining: 206ms
797:	learn: 0.2894085	total: 810ms	remaining: 205ms
798:	learn: 0.2892808	total: 811ms	remaining: 204ms
799:	learn: 0.2890993	total: 812ms	remaining: 203ms
800:	learn: 0.2890907	total: 813ms	remaining: 202ms
801:	learn: 0.2890101	total: 814ms	remaining: 201ms
802:	learn: 0.2889190	total: 815ms	remaining: 200ms
803:	learn: 0.2888300	total: 816ms	remaining: 199ms
804:	learn: 0.2887533	total: 817ms	remaining: 198ms
805:	learn: 0.2887056	total: 818ms	remaining: 197ms
806:	learn: 

947:	learn: 0.2751601	total: 969ms	remaining: 53.1ms
948:	learn: 0.2748834	total: 970ms	remaining: 52.1ms
949:	learn: 0.2746793	total: 971ms	remaining: 51.1ms
950:	learn: 0.2746129	total: 972ms	remaining: 50.1ms
951:	learn: 0.2745740	total: 973ms	remaining: 49.1ms
952:	learn: 0.2745488	total: 974ms	remaining: 48ms
953:	learn: 0.2745005	total: 975ms	remaining: 47ms
954:	learn: 0.2744392	total: 976ms	remaining: 46ms
955:	learn: 0.2743191	total: 977ms	remaining: 45ms
956:	learn: 0.2742770	total: 978ms	remaining: 44ms
957:	learn: 0.2742325	total: 979ms	remaining: 42.9ms
958:	learn: 0.2741868	total: 981ms	remaining: 41.9ms
959:	learn: 0.2741287	total: 982ms	remaining: 40.9ms
960:	learn: 0.2740911	total: 983ms	remaining: 39.9ms
961:	learn: 0.2740217	total: 984ms	remaining: 38.9ms
962:	learn: 0.2739612	total: 985ms	remaining: 37.9ms
963:	learn: 0.2739056	total: 987ms	remaining: 36.8ms
964:	learn: 0.2738729	total: 988ms	remaining: 35.8ms
965:	learn: 0.2736047	total: 989ms	remaining: 34.8ms
966

240:	learn: 0.3862958	total: 252ms	remaining: 793ms
241:	learn: 0.3859420	total: 253ms	remaining: 793ms
242:	learn: 0.3857446	total: 254ms	remaining: 793ms
243:	learn: 0.3855503	total: 256ms	remaining: 792ms
244:	learn: 0.3853234	total: 257ms	remaining: 792ms
245:	learn: 0.3852429	total: 258ms	remaining: 791ms
246:	learn: 0.3850282	total: 259ms	remaining: 791ms
247:	learn: 0.3846553	total: 261ms	remaining: 790ms
248:	learn: 0.3843673	total: 262ms	remaining: 790ms
249:	learn: 0.3841998	total: 263ms	remaining: 789ms
250:	learn: 0.3838316	total: 265ms	remaining: 790ms
251:	learn: 0.3837309	total: 267ms	remaining: 792ms
252:	learn: 0.3834067	total: 268ms	remaining: 792ms
253:	learn: 0.3831478	total: 269ms	remaining: 791ms
254:	learn: 0.3827806	total: 271ms	remaining: 791ms
255:	learn: 0.3825402	total: 272ms	remaining: 791ms
256:	learn: 0.3824222	total: 274ms	remaining: 792ms
257:	learn: 0.3821319	total: 276ms	remaining: 792ms
258:	learn: 0.3818795	total: 277ms	remaining: 792ms
259:	learn: 

553:	learn: 0.3411935	total: 587ms	remaining: 473ms
554:	learn: 0.3411790	total: 588ms	remaining: 471ms
555:	learn: 0.3411015	total: 589ms	remaining: 470ms
556:	learn: 0.3410822	total: 590ms	remaining: 469ms
557:	learn: 0.3409101	total: 591ms	remaining: 468ms
558:	learn: 0.3408341	total: 592ms	remaining: 467ms
559:	learn: 0.3406990	total: 593ms	remaining: 466ms
560:	learn: 0.3405438	total: 594ms	remaining: 465ms
561:	learn: 0.3404996	total: 595ms	remaining: 464ms
562:	learn: 0.3403541	total: 596ms	remaining: 463ms
563:	learn: 0.3401672	total: 597ms	remaining: 462ms
564:	learn: 0.3400831	total: 598ms	remaining: 461ms
565:	learn: 0.3399919	total: 600ms	remaining: 460ms
566:	learn: 0.3399262	total: 601ms	remaining: 459ms
567:	learn: 0.3399042	total: 601ms	remaining: 457ms
568:	learn: 0.3398435	total: 602ms	remaining: 456ms
569:	learn: 0.3396913	total: 603ms	remaining: 455ms
570:	learn: 0.3395973	total: 605ms	remaining: 454ms
571:	learn: 0.3394817	total: 606ms	remaining: 453ms
572:	learn: 

712:	learn: 0.3239799	total: 756ms	remaining: 304ms
713:	learn: 0.3239438	total: 757ms	remaining: 303ms
714:	learn: 0.3238598	total: 758ms	remaining: 302ms
715:	learn: 0.3237654	total: 759ms	remaining: 301ms
716:	learn: 0.3236178	total: 760ms	remaining: 300ms
717:	learn: 0.3235604	total: 761ms	remaining: 299ms
718:	learn: 0.3234450	total: 762ms	remaining: 298ms
719:	learn: 0.3233481	total: 763ms	remaining: 297ms
720:	learn: 0.3231734	total: 764ms	remaining: 296ms
721:	learn: 0.3231105	total: 765ms	remaining: 294ms
722:	learn: 0.3230475	total: 766ms	remaining: 293ms
723:	learn: 0.3229692	total: 767ms	remaining: 292ms
724:	learn: 0.3229590	total: 768ms	remaining: 291ms
725:	learn: 0.3228978	total: 769ms	remaining: 290ms
726:	learn: 0.3228532	total: 770ms	remaining: 289ms
727:	learn: 0.3227659	total: 772ms	remaining: 288ms
728:	learn: 0.3226958	total: 773ms	remaining: 287ms
729:	learn: 0.3225979	total: 774ms	remaining: 286ms
730:	learn: 0.3224650	total: 775ms	remaining: 285ms
731:	learn: 

874:	learn: 0.3059413	total: 925ms	remaining: 132ms
875:	learn: 0.3059144	total: 927ms	remaining: 131ms
876:	learn: 0.3059040	total: 927ms	remaining: 130ms
877:	learn: 0.3056399	total: 929ms	remaining: 129ms
878:	learn: 0.3055959	total: 930ms	remaining: 128ms
879:	learn: 0.3054521	total: 931ms	remaining: 127ms
880:	learn: 0.3052749	total: 932ms	remaining: 126ms
881:	learn: 0.3051827	total: 933ms	remaining: 125ms
882:	learn: 0.3051466	total: 933ms	remaining: 124ms
883:	learn: 0.3050751	total: 934ms	remaining: 123ms
884:	learn: 0.3049854	total: 935ms	remaining: 122ms
885:	learn: 0.3048870	total: 936ms	remaining: 120ms
886:	learn: 0.3047771	total: 937ms	remaining: 119ms
887:	learn: 0.3046517	total: 938ms	remaining: 118ms
888:	learn: 0.3046166	total: 939ms	remaining: 117ms
889:	learn: 0.3044830	total: 941ms	remaining: 116ms
890:	learn: 0.3044318	total: 942ms	remaining: 115ms
891:	learn: 0.3043722	total: 943ms	remaining: 114ms
892:	learn: 0.3042350	total: 944ms	remaining: 113ms
893:	learn: 

In [36]:
#SVR
classifier = SVR(kernel = 'rbf',)
classifier.fit(X_train_scaled, y_train)

accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print('SVR:')
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

SVR:
Accuracy: -2.67 %
Standard Deviation: 10.47 %


In [38]:
##Polynomial Regression deg = 2
poly_reg_2 = PolynomialFeatures(degree = 2)
X_poly = poly_reg_2.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print('Polynomial Regression:')
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Polynomial Regression:
Accuracy: -2.67 %
Standard Deviation: 10.47 %


## Submission

The best Score was with our Cat Boost:

In [39]:
print(X_test)

[[1.0 0.0 0.0 3 1 29.69911764705882 1 1 15.2458]
 [0.0 0.0 1.0 2 1 31.0 0 0 10.5]
 [0.0 0.0 1.0 3 1 20.0 0 0 7.925]
 [0.0 0.0 1.0 2 0 6.0 0 1 33.0]
 [1.0 0.0 0.0 3 0 14.0 1 0 11.2417]
 [0.0 0.0 1.0 1 0 26.0 0 0 78.85]
 [0.0 1.0 0.0 3 0 29.69911764705882 0 0 7.75]
 [0.0 0.0 1.0 3 1 16.0 2 0 18.0]
 [0.0 1.0 0.0 3 0 16.0 0 0 7.75]
 [0.0 0.0 1.0 1 0 19.0 0 2 26.2833]
 [0.0 0.0 1.0 1 1 37.0 1 0 53.1]
 [0.0 0.0 1.0 3 1 44.0 0 0 8.05]
 [0.0 0.0 1.0 3 0 29.69911764705882 3 1 25.4667]
 [1.0 0.0 0.0 3 1 30.0 0 0 7.225]
 [0.0 0.0 1.0 2 1 36.0 0 0 13.0]
 [0.0 0.0 1.0 1 0 16.0 0 1 39.4]
 [0.0 0.0 1.0 1 1 42.0 1 0 52.5542]
 [0.0 1.0 0.0 3 0 29.69911764705882 0 0 7.8292]
 [0.0 0.0 1.0 2 1 27.0 0 0 13.0]
 [0.0 0.0 1.0 1 1 47.0 0 0 52.0]
 [0.0 0.0 1.0 3 1 24.0 0 0 7.8958]
 [0.0 0.0 1.0 1 1 34.0 0 0 26.55]
 [0.0 0.0 1.0 3 0 19.0 1 0 7.8542]
 [0.0 0.0 1.0 3 1 20.0 0 0 9.225]
 [0.0 0.0 1.0 3 1 29.69911764705882 0 0 14.5]
 [0.0 0.0 1.0 3 1 10.0 3 2 27.9]
 [1.0 0.0 0.0 1 1 40.0 0 0 27.7208]
 [0.0 0.0 1.0 2 

In [40]:
##Feature Scaling

sc = StandardScaler()

ct = ColumnTransformer(transformers = [('somename',sc,[5,-1])], remainder = 'passthrough')##Encoding the Embarked columns
X_train = np.array(ct.fit_transform(X_train))
X_test = np.array(ct.fit_transform(X_test))
test_dataset = np.array(ct.fit_transform(test_dataset))

In [41]:
test_dataset

array([[0.534896093161581, -0.4984070560437162, 0.0, 1.0, 0.0, 3, 1,
        34.5, 0],
       [1.409210078886808, -0.5132742875713459, 0.0, 0.0, 1.0, 3, 0,
        47.0, 0],
       [2.4583868617570803, -0.4650884642108722, 0.0, 1.0, 0.0, 2, 1,
        62.0, 0],
       [0.010307701726444875, -0.4834663131204482, 0.0, 0.0, 1.0, 3, 1,
        27.0, 0],
       [-0.3394178925636459, -0.4184714816109721, 0.0, 0.0, 1.0, 3, 0,
        22.0, 1],
       [-0.8989788434277912, -0.4733809082310467, 0.0, 0.0, 1.0, 3, 1,
        14.0, 0],
       [0.22014305830049935, -0.50199297778217, 0.0, 1.0, 0.0, 3, 0,
        30.0, 0],
       [-0.059637417131573285, -0.11882289634142197, 0.0, 0.0, 1.0, 2, 1,
        26.0, 1],
       [-0.6191983679957186, -0.5091648212590778, 1.0, 0.0, 0.0, 3, 0,
        18.0, 0],
       [-0.4093630114216641, -0.20578149849892796, 0.0, 0.0, 1.0, 3, 1,
        21.0, 0],
       [-0.9234596350280976, -0.49721294410481104, 0.0, 0.0, 1.0, 3, 1,
        13.65, 0],
       [1.33926496002

In [42]:
#Cat Boost
classifier = CatBoostClassifier()
classifier.fit(X_train, y_train)

Learning rate set to 0.008911
0:	learn: 0.6866880	total: 2.21ms	remaining: 2.21s
1:	learn: 0.6798537	total: 4.18ms	remaining: 2.09s
2:	learn: 0.6743733	total: 5.96ms	remaining: 1.98s
3:	learn: 0.6687697	total: 7.55ms	remaining: 1.88s
4:	learn: 0.6637420	total: 8.41ms	remaining: 1.67s
5:	learn: 0.6583842	total: 9.95ms	remaining: 1.65s
6:	learn: 0.6529471	total: 11.4ms	remaining: 1.62s
7:	learn: 0.6480498	total: 12.8ms	remaining: 1.59s
8:	learn: 0.6436408	total: 13.5ms	remaining: 1.49s
9:	learn: 0.6389590	total: 14.4ms	remaining: 1.43s
10:	learn: 0.6346292	total: 15.9ms	remaining: 1.43s
11:	learn: 0.6292764	total: 17.2ms	remaining: 1.42s
12:	learn: 0.6244014	total: 18.4ms	remaining: 1.4s
13:	learn: 0.6196515	total: 20.1ms	remaining: 1.41s
14:	learn: 0.6145737	total: 21.5ms	remaining: 1.41s
15:	learn: 0.6103729	total: 22.7ms	remaining: 1.4s
16:	learn: 0.6059554	total: 23.6ms	remaining: 1.36s
17:	learn: 0.6017323	total: 24.6ms	remaining: 1.34s
18:	learn: 0.5969899	total: 25.6ms	remaining: 

309:	learn: 0.3588159	total: 326ms	remaining: 726ms
310:	learn: 0.3586848	total: 328ms	remaining: 726ms
311:	learn: 0.3585525	total: 329ms	remaining: 725ms
312:	learn: 0.3584976	total: 330ms	remaining: 724ms
313:	learn: 0.3583473	total: 331ms	remaining: 723ms
314:	learn: 0.3580103	total: 332ms	remaining: 722ms
315:	learn: 0.3578686	total: 333ms	remaining: 720ms
316:	learn: 0.3578531	total: 334ms	remaining: 719ms
317:	learn: 0.3575927	total: 335ms	remaining: 718ms
318:	learn: 0.3575279	total: 336ms	remaining: 717ms
319:	learn: 0.3573395	total: 337ms	remaining: 716ms
320:	learn: 0.3571888	total: 338ms	remaining: 715ms
321:	learn: 0.3569960	total: 339ms	remaining: 713ms
322:	learn: 0.3565910	total: 340ms	remaining: 712ms
323:	learn: 0.3564528	total: 341ms	remaining: 712ms
324:	learn: 0.3563217	total: 342ms	remaining: 711ms
325:	learn: 0.3561688	total: 344ms	remaining: 710ms
326:	learn: 0.3560013	total: 345ms	remaining: 709ms
327:	learn: 0.3559421	total: 346ms	remaining: 709ms
328:	learn: 

476:	learn: 0.3379513	total: 495ms	remaining: 543ms
477:	learn: 0.3379315	total: 496ms	remaining: 541ms
478:	learn: 0.3378935	total: 497ms	remaining: 540ms
479:	learn: 0.3376918	total: 498ms	remaining: 540ms
480:	learn: 0.3373157	total: 499ms	remaining: 539ms
481:	learn: 0.3372356	total: 500ms	remaining: 538ms
482:	learn: 0.3371704	total: 501ms	remaining: 536ms
483:	learn: 0.3370264	total: 502ms	remaining: 535ms
484:	learn: 0.3368555	total: 503ms	remaining: 534ms
485:	learn: 0.3367100	total: 504ms	remaining: 533ms
486:	learn: 0.3366850	total: 505ms	remaining: 532ms
487:	learn: 0.3366003	total: 506ms	remaining: 531ms
488:	learn: 0.3365166	total: 508ms	remaining: 530ms
489:	learn: 0.3364129	total: 509ms	remaining: 529ms
490:	learn: 0.3363290	total: 510ms	remaining: 529ms
491:	learn: 0.3361362	total: 511ms	remaining: 528ms
492:	learn: 0.3360365	total: 512ms	remaining: 527ms
493:	learn: 0.3359179	total: 513ms	remaining: 526ms
494:	learn: 0.3356703	total: 514ms	remaining: 525ms
495:	learn: 

643:	learn: 0.3194588	total: 663ms	remaining: 366ms
644:	learn: 0.3193336	total: 664ms	remaining: 366ms
645:	learn: 0.3190958	total: 665ms	remaining: 365ms
646:	learn: 0.3190675	total: 667ms	remaining: 364ms
647:	learn: 0.3189890	total: 668ms	remaining: 363ms
648:	learn: 0.3188888	total: 669ms	remaining: 362ms
649:	learn: 0.3188776	total: 670ms	remaining: 361ms
650:	learn: 0.3186574	total: 671ms	remaining: 360ms
651:	learn: 0.3185126	total: 672ms	remaining: 359ms
652:	learn: 0.3183060	total: 673ms	remaining: 358ms
653:	learn: 0.3182477	total: 674ms	remaining: 357ms
654:	learn: 0.3180269	total: 675ms	remaining: 356ms
655:	learn: 0.3178969	total: 676ms	remaining: 355ms
656:	learn: 0.3178405	total: 677ms	remaining: 354ms
657:	learn: 0.3177784	total: 678ms	remaining: 353ms
658:	learn: 0.3176897	total: 679ms	remaining: 352ms
659:	learn: 0.3175633	total: 680ms	remaining: 351ms
660:	learn: 0.3174426	total: 681ms	remaining: 349ms
661:	learn: 0.3173165	total: 682ms	remaining: 348ms
662:	learn: 

810:	learn: 0.3015446	total: 834ms	remaining: 194ms
811:	learn: 0.3015123	total: 835ms	remaining: 193ms
812:	learn: 0.3014542	total: 837ms	remaining: 192ms
813:	learn: 0.3012728	total: 838ms	remaining: 192ms
814:	learn: 0.3010798	total: 839ms	remaining: 191ms
815:	learn: 0.3010752	total: 840ms	remaining: 189ms
816:	learn: 0.3009896	total: 841ms	remaining: 188ms
817:	learn: 0.3009103	total: 842ms	remaining: 187ms
818:	learn: 0.3007632	total: 844ms	remaining: 186ms
819:	learn: 0.3006205	total: 845ms	remaining: 185ms
820:	learn: 0.3004790	total: 846ms	remaining: 185ms
821:	learn: 0.3004003	total: 848ms	remaining: 184ms
822:	learn: 0.3001341	total: 849ms	remaining: 183ms
823:	learn: 0.3000778	total: 850ms	remaining: 182ms
824:	learn: 0.2999326	total: 851ms	remaining: 180ms
825:	learn: 0.2998694	total: 852ms	remaining: 179ms
826:	learn: 0.2997684	total: 853ms	remaining: 178ms
827:	learn: 0.2997109	total: 854ms	remaining: 177ms
828:	learn: 0.2997070	total: 854ms	remaining: 176ms
829:	learn: 

967:	learn: 0.2845134	total: 1s	remaining: 33.2ms
968:	learn: 0.2844101	total: 1s	remaining: 32.1ms
969:	learn: 0.2842753	total: 1s	remaining: 31.1ms
970:	learn: 0.2842222	total: 1.01s	remaining: 30.1ms
971:	learn: 0.2841576	total: 1.01s	remaining: 29ms
972:	learn: 0.2840911	total: 1.01s	remaining: 28ms
973:	learn: 0.2840372	total: 1.01s	remaining: 27ms
974:	learn: 0.2838227	total: 1.01s	remaining: 25.9ms
975:	learn: 0.2837556	total: 1.01s	remaining: 24.9ms
976:	learn: 0.2835910	total: 1.01s	remaining: 23.9ms
977:	learn: 0.2835028	total: 1.01s	remaining: 22.8ms
978:	learn: 0.2834493	total: 1.02s	remaining: 21.8ms
979:	learn: 0.2833618	total: 1.02s	remaining: 20.8ms
980:	learn: 0.2832490	total: 1.02s	remaining: 19.7ms
981:	learn: 0.2831515	total: 1.02s	remaining: 18.7ms
982:	learn: 0.2829863	total: 1.02s	remaining: 17.6ms
983:	learn: 0.2827290	total: 1.02s	remaining: 16.6ms
984:	learn: 0.2826888	total: 1.02s	remaining: 15.6ms
985:	learn: 0.2824707	total: 1.02s	remaining: 14.5ms
986:	lea

In [45]:
y_pred = classifier.predict(test_dataset)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [46]:
submission = pd.Series(y_pred, index=test_dataset_2_sub['PassengerId'], name='Survived')
submission

PassengerId
892     0
893     0
894     0
895     0
896     0
       ..
1305    0
1306    1
1307    0
1308    0
1309    0
Name: Survived, Length: 418, dtype: int64

In [47]:
submission.to_csv("model_5.csv", header=True)